CREATE TABLE graph_tag_idcard_base ( -- 人员信息综合表
    source TEXT,                -- 来源
    source_name TEXT,           -- 来源
    etl_time DATETIME,          -- 同步时间
    batch TEXT,                 -- 批次
    gmsfhm TEXT,                -- 身份证号码
    xm TEXT,                    -- 姓名
    lxdh TEXT,                  -- 联系电话
    hh TEXT,                    -- 户号
    yhzgxdm TEXT,               -- 与户主关系
    yhzgxdm_detail TEXT,        -- 与户主关系
    cym TEXT,                   -- 曾用名
    xbdm TEXT,                  -- 性别
    xbdm_detail TEXT,           -- 性别
    mzdm TEXT,                  -- 民族
    mzdm_detail TEXT,           -- 民族
    csrq TEXT,                  -- 出生日期
    xldm TEXT,                  -- 学历
    xldm_detail TEXT,           -- 学历
    hyzkdm TEXT,                -- 婚姻状况
    hyzkdm_detail TEXT,         -- 婚姻状况
    cyzk_bm TEXT,               -- 从业状况单位编码
    cyzk_mc TEXT,               -- 从业状况单位名称
    cyzk_zylbdm TEXT,           -- 从业状况职业编码
    cyzk_zy TEXT,               -- 从业状况职业
    zjxydm TEXT,                -- 宗教信仰
    zjxydm_detail TEXT,         -- 宗教信仰
    byzkdm TEXT,                -- 兵役状况
    byzkdm_detail TEXT,         -- 兵役状况
    sg TEXT,                    -- 身高
    xxdm TEXT,                  -- 血型
    xxdm_detail TEXT,           -- 血型
    swrq TEXT,                  -- 死亡日期
    rkglswyydm TEXT,            -- 死亡原因
    rkglswyydm_detail TEXT,     -- 死亡原因
    jg_ssxqdm TEXT,             -- 籍贯-省市县（区）
    jg_ssxqdm_detail TEXT,      -- 籍贯-省市县（区）
    jg_qhnxxdz TEXT,            -- 籍贯-区划内详细地址
    hjdz_ssxqdm TEXT,           -- 户籍-省市县（区）
    hjdz_ssxqdm_detail TEXT,    -- 户籍-省市县（区）
    hjdz_qhnxxdz TEXT,          -- 户籍-区划内详细地址
    cyjmsfzqk_qfjg_gajgmc TEXT, -- 签发机关
    cyjmsfzqk_yxqqsrq TEXT,     -- 有效期起始日期
    cyjmsfzqk_yxqjzrq TEXT,     -- 有效期截止日期
    sjgsdwdm TEXT,              -- 管辖单位(派出所)
    sjgsdwmc TEXT,              -- 管辖单位(派出所)
    qrrq TEXT,                  -- 迁入日期
    qryy TEXT,                  -- 迁入原因
    qryy_detail TEXT,           -- 迁入原因
    lzdq_ssxqdm TEXT,           -- 来自地区
    lzdq_ssxqdm_detail TEXT,    -- 来自地区
    lzdq_qhnxxdz TEXT,          -- 来自详细地址
    qcrq TEXT,                  -- 迁出日期
    qcyy TEXT,                  -- 迁出原因
    qcyy_detail TEXT,           -- 迁出原因
    qcdq_ssxqdm TEXT,           -- 迁出地区
    qcdq_ssxqdm_detail TEXT,    -- 迁出地区
    qcdq_qhnxxdz TEXT,          -- 迁出详细地址
    rkzt TEXT,                  -- 人口状态
    add_time DATETIME           -- 添加时间
);

CREATE TABLE rzx_wz_wldt_logs ( -- 网络轨迹表
    data_type TEXT,         -- 数据类型（4g,gw,wb,sj）
    app_type TEXT,          -- 来源表名（英文）
    app_type_name TEXT,     -- 来源表名（中文）
    protocol_type TEXT,     -- 协议英文（软件名称）
    protocol_type_name TEXT, -- 协议中文
    action TEXT,            -- 操作动作，例如发帖（字典）
    auth_account TEXT,      -- 认证账号（宽带账号，手机号,身份证）
    user_id TEXT,           -- 账号id
    username TEXT,          -- 账号
    nickname TEXT,          -- 昵称
    title TEXT,             -- 标题
    content TEXT,           -- 内容
    imgs TEXT,              -- 图片列表，文件列表
    tags TEXT,              -- 标签列表
    url TEXT,               -- 访问url
    capture_time TEXT,      -- 采集时间(13位时间戳)
    to_user_id TEXT,        -- 接收账号id
    to_username TEXT,       -- 接收账号
    to_nickname TEXT,       -- 接收昵称
    isp_id TEXT,            -- 运营商名称（汉字）
    base_station_id TEXT,   -- 基站ID
    equipment_id TEXT,      -- 设备id（IMEI）
    imsi TEXT,              -- IMSI
    longitude TEXT,         -- 经度
    latitude TEXT,          -- 纬度
    src_ip TEXT,            -- 源ip
    src_port TEXT,          -- 源端口
    dst_ip TEXT,            -- 目的ip
    dst_port TEXT,          -- 目的端口
    domain TEXT,            -- 域名
    password TEXT,          -- 密码
    other_info TEXT,        -- 其他信息
    mac TEXT,               -- mac
    keyword TEXT,           -- 关键词
    is_domestic TEXT,       -- 是否境内ip
    src_ip_address TEXT,    -- 具体地址
    dst_ip_address TEXT     -- 具体地址
);

CREATE TABLE res_0_clda_jdc (  -- 车辆信息表
    hphm TEXT,                 -- 号牌号码
    hpzl TEXT,                 -- 号牌种类
    hpzl_detail TEXT,          -- 号牌种类详情
    hpys TEXT,                 -- 号牌颜色
    clsbdh TEXT,               -- 车辆识别代号
    syr TEXT,                  -- 机动车所有人
    sfzmhm TEXT,               -- 身份证明号码
    sfzmmc TEXT,               -- 身份证明名称
    sfzmmc_detail TEXT,        -- 身份证明名称详情
    lxdh TEXT,                 -- 联系电话
    zsxxdz TEXT,               -- 住所详细地址
    clpp2 TEXT,                -- 英文品牌
    clpp1 TEXT,                -- 中文品牌
    clxh TEXT,                 -- 车辆型号
    cldl TEXT,                 -- 车辆大类
    cldl_detail TEXT,          -- 车辆大类详情
    cllx TEXT,                 -- 车辆类型
    cllx_detail TEXT,          -- 车辆类型详情
    csys TEXT,                 -- 车身颜色
    csys_detail TEXT,          -- 车身颜色详情
    syxz TEXT,                 -- 使用性质
    syxz_detail TEXT,          -- 使用性质详情
    zt TEXT,                   -- 机动车状态
    ccdjrq TEXT,               -- 初次登记日期
    fprq TEXT,                 -- 发牌日期
    fzrq TEXT,                 -- 发行驶证日期
    syqsrq TEXT,               -- 使用起始日期
    djrq TEXT,                 -- 最近定检日期
    fhgzrq TEXT,               -- 发合格证日期
    yxqz TEXT,                 -- 检验有效期止
    qzbfqz TEXT,               -- 强制报废期止
    bxzzrq TEXT,               -- 保险终止日期
    ccrq TEXT,                 -- 出厂日期
    clyt TEXT,                 -- 车辆用途
    sjhm TEXT,                 -- 手机号码
    clly TEXT,                 -- 1注册2转入3过户
    ncdqsy TEXT,               -- 是否为农村地区使用1-是；2-否
    zzg TEXT,                  -- 制造国
    yxh TEXT,                  -- 原机动车序号
    hdzk TEXT,                 -- 核定载客
    zzl TEXT,                  -- 总质量
    zxxs_detail TEXT,          -- 转向形式详情
    dzyx TEXT,                 -- 电子邮箱
    wxmbc_detail TEXT,         -- 是否为微型面包车详情
    hpzk TEXT,                 -- 驾驶室后排载客人数
    zzz TEXT,                  -- 暂住居住证明
    jbr TEXT,                  -- 经办人
    yqjyqz2 TEXT,              -- 逾期2个检验周期期止
    zsxzqh TEXT,               -- 住所行政区划
    bpcs TEXT,                 -- 补领号牌次数
    cyry TEXT,                 -- 查验人员
    gbthps TEXT,               -- 钢板弹簧片数
    jkpz TEXT,                 -- 进口凭证
    jyhgbzbh TEXT,             -- 检验合格标志
    hmbh TEXT,                 -- 后膜编号
    zzxzqh_detail TEXT,        -- 暂住行政区划详情
    nszmbh TEXT,               -- 纳税证明编号
    zj TEXT,                   -- 轴距
    fzjg TEXT,                 -- 发证机关
    dwbh TEXT,                 -- 单位编号
    zs TEXT,                   -- 轴数
    gcjk TEXT,                 -- 国产/进口
    wxmbc TEXT,                -- 是否为微型面包车1-是；2-否
    sqdm TEXT,                 -- 社区代码
    dybj_detail TEXT,          -- 是否抵押详情
    qmbh TEXT,                 -- 前膜编号
    xgzl TEXT,                 -- 相关资料
    zzg_detail TEXT,           -- 制造国详情
    ltgg TEXT,                 -- 轮胎规格
    xsjg TEXT,                 -- 销售价格
    xsrq TEXT,                 -- 销售日期
    zdjzshs TEXT,              -- 制登记证书行数
    clly_detail TEXT,          -- 车辆来源详情
    bz TEXT,                   -- 备注
    fdjh TEXT,                 -- 发动机号
    zsxzqh_detail TEXT,        -- 住所行政区划详情
    rlzl_detail TEXT,          -- 燃料种类详情
    xzqh_detail TEXT,          -- 管理辖区详情
    gcjk_detail TEXT,          -- 国产/进口详情
    zzjglx TEXT,               -- 组织机构类型
    zzxxdz TEXT,               -- 暂住详细地址
    zzxzqh TEXT,               -- 暂住行政区划
    fdjrq TEXT,                -- 发登记证书日期
    zbzl TEXT,                 -- 整备质量
    dphgzbh TEXT,              -- 底盘合格证编号
    etl_date TEXT,             -- ETL_DATE
    hxnbgd TEXT,               -- 货箱内部高度
    bdjcs TEXT,                -- 补/换领证书次数
    hdfs_detail TEXT,          -- 获得方式详情
    djzsbh TEXT,               -- 登记证书编号
    odc_cqsj TEXT,             -- ODC抽取时间
    hdzzl TEXT,                -- 核定载质量
    hbdbqk TEXT,               -- 环保达标情况
    qlj TEXT,                  -- 前轮距
    zxxs TEXT,                 -- 转向形式
    yzbm1 TEXT,                -- 住所邮政编码
    yzbm2 TEXT,                -- 暂住邮政编码
    nszm TEXT,                 -- 纳税证明
    dabh TEXT,                 -- 档案编号
    lsh TEXT,                  -- 注册流水号
    yqjyqzbfqz TEXT,           -- 逾期检验强制报废期止
    zt_detail TEXT,            -- 机动车状态详情
    syq TEXT,                  -- 所有权
    odc_zj TEXT,               -- ODC主键
    zqyzl TEXT,                -- 准牵引总质量
    xzqh TEXT,                 -- 管理辖区
    odc_jcbz TEXT,             -- ODC检查标志
    llpz1 TEXT,                -- 来历凭证1
    qpzk TEXT,                 -- 驾驶室前排载客人数
    xszbh TEXT,                -- 行驶证证芯编号
    llpz2 TEXT,                -- 来历凭证2
    dybj TEXT,                 -- 0-未抵押，1-已抵押
    fdjgs TEXT,                -- 发动机缸数
    hxnbkd TEXT,               -- 货箱内部宽度
    fdjxh TEXT,                -- 发动机型号
    hlj TEXT,                  -- 后轮距
    zzcmc TEXT,                -- 制造厂名称
    lts TEXT,                  -- 轮胎数
    rlzl TEXT,                 -- 燃料种类
    cwkk TEXT,                 -- 车外廓宽
    odc_gxsj TEXT,             -- ODC更新时间
    cwkg TEXT,                 -- 车外廓高
    gxrq TEXT,                 -- 更新日期
    glbm TEXT,                 -- 管理部门
    sfyzhgn TEXT,              -- 专项做车是否有载货功能1-是；2-否
    cwkc TEXT,                 -- 车外廓长
    bzcs TEXT,                 -- 补领行驶证次数
    hgzbh TEXT,                -- 合格证编号
    jkpzhm TEXT,               -- 进口凭证编号
    gl TEXT,                   -- 功率
    xsdw TEXT,                 -- 销售单位
    hdfs TEXT,                 -- 获得方式
    ytsx TEXT,                 -- 用途属性
    jyw TEXT,                  -- 校验位
    pzbh1 TEXT,                -- 凭证编号1
    xh TEXT,                   -- 机动车序号
    pzbh2 TEXT,                -- 凭证编号2
    hxnbcd TEXT,               -- 货箱内部长度
    pl TEXT,                   -- 排量
    zdyzt TEXT,                -- 自定义状态
    rzx_uuid TEXT,             -- rzx唯一编码
    kafka_createtime TEXT,     -- 接入kafka时间
    createtime_rzx TEXT,       -- 原表入库时间
    rzx_src TEXT,              -- 数据溯源
    rzx_id TEXT,               -- rzx根据规则生成的数据id
    rzx_src2 TEXT,             -- 数据溯源2
    inserttime_rzx TEXT,       -- 入库时间
    ch_partition TEXT          -- 分区字段
);

CREATE TABLE res_zh_gj_info (       -- 人员轨迹表
    id TEXT,                        -- 唯一标识
    trace_type TEXT,                -- 轨迹类型
    trace_type_name TEXT,           -- 轨迹类型名称
    id_card TEXT,                   -- 身份证号
    name TEXT,                      -- 姓名
    from_place TEXT,                -- 开始地点
    to_place TEXT,                  -- 到达地点
    start_time DATETIME,            -- 开始时间
    end_time DATETIME,              -- 到达时间
    batch_no TEXT,                  -- 轨迹批次
    trace_status TEXT,              -- 轨迹状态
    trace_status_name TEXT,         -- 轨迹状态名称
    phone_no TEXT,                  -- 手机号
    detail_info TEXT,               -- 详细信息
    trace_source TEXT,              -- 轨迹来源(表名)
    trace_source_name TEXT,         -- 轨迹来源(表中文名)
    remark TEXT,                    -- 备注
    capture_time DATETIME,          -- 采集时间
    address TEXT,                   -- 具体位置
    createtime_rzx TEXT,            -- 数据入ck时间
    create_time DATETIME,           -- 创建时间
    create_date DATE,               -- 创建时间
    car_number TEXT,                -- 车牌号
    from_place_location_code TEXT,  -- 出发地CODE
    to_place_location_code TEXT,    -- 到达地CODE
    from_place_longitude TEXT,      -- 出发地经度
    from_place_latitude TEXT,       -- 出发地纬度
    to_place_longitude TEXT,        -- 到达地经度
    to_place_latitude TEXT,         -- 到达地纬度
    from_place_address TEXT,        -- 出发地地址
    to_place_address TEXT,          -- 到达地地址
    hjdz_ssxqdm TEXT,               -- 户籍地代码（370102）
    hjdz_ssxqdm_detail TEXT,        -- 户籍地详细地址
    hjdz_qhnxxdz TEXT               -- 户籍地区划地（山东省济南市历下区）
);