CREATE TABLE graph_tag_idcard_base ( -- 人员信息综合表
    source TEXT,                -- 来源
    source_name TEXT,           -- 来源
    etl_time DATETIME,          -- 同步时间
    batch TEXT,                 -- 批次
    gmsfhm TEXT,                -- 身份证号码
    xm TEXT,                    -- 姓名
    lxdh TEXT,                  -- 联系电话
    hh TEXT,                    -- 户号
    yhzgxdm TEXT,               -- 与户主关系
    yhzgxdm_detail TEXT,        -- 与户主关系
    cym TEXT,                   -- 曾用名
    xbdm TEXT,                  -- 性别
    xbdm_detail TEXT,           -- 性别
    mzdm TEXT,                  -- 民族
    mzdm_detail TEXT,           -- 民族
    csrq TEXT,                  -- 出生日期
    xldm TEXT,                  -- 学历
    xldm_detail TEXT,           -- 学历
    hyzkdm TEXT,                -- 婚姻状况
    hyzkdm_detail TEXT,         -- 婚姻状况
    cyzk_bm TEXT,               -- 从业状况单位编码
    cyzk_mc TEXT,               -- 从业状况单位名称
    cyzk_zylbdm TEXT,           -- 从业状况职业编码
    cyzk_zy TEXT,               -- 从业状况职业
    zjxydm TEXT,                -- 宗教信仰
    zjxydm_detail TEXT,         -- 宗教信仰
    byzkdm TEXT,                -- 兵役状况
    byzkdm_detail TEXT,         -- 兵役状况
    sg TEXT,                    -- 身高
    xxdm TEXT,                  -- 血型
    xxdm_detail TEXT,           -- 血型
    swrq TEXT,                  -- 死亡日期
    rkglswyydm TEXT,            -- 死亡原因
    rkglswyydm_detail TEXT,     -- 死亡原因
    jg_ssxqdm TEXT,             -- 籍贯-省市县（区）
    jg_ssxqdm_detail TEXT,      -- 籍贯-省市县（区）
    jg_qhnxxdz TEXT,            -- 籍贯-区划内详细地址
    hjdz_ssxqdm TEXT,           -- 户籍-省市县（区）
    hjdz_ssxqdm_detail TEXT,    -- 户籍-省市县（区）
    hjdz_qhnxxdz TEXT,          -- 户籍-区划内详细地址
    cyjmsfzqk_qfjg_gajgmc TEXT, -- 签发机关
    cyjmsfzqk_yxqqsrq TEXT,     -- 有效期起始日期
    cyjmsfzqk_yxqjzrq TEXT,     -- 有效期截止日期
    sjgsdwdm TEXT,              -- 管辖单位(派出所)
    sjgsdwmc TEXT,              -- 管辖单位(派出所)
    qrrq TEXT,                  -- 迁入日期
    qryy TEXT,                  -- 迁入原因
    qryy_detail TEXT,           -- 迁入原因
    lzdq_ssxqdm TEXT,           -- 来自地区
    lzdq_ssxqdm_detail TEXT,    -- 来自地区
    lzdq_qhnxxdz TEXT,          -- 来自详细地址
    qcrq TEXT,                  -- 迁出日期
    qcyy TEXT,                  -- 迁出原因
    qcyy_detail TEXT,           -- 迁出原因
    qcdq_ssxqdm TEXT,           -- 迁出地区
    qcdq_ssxqdm_detail TEXT,    -- 迁出地区
    qcdq_qhnxxdz TEXT,          -- 迁出详细地址
    rkzt TEXT,                  -- 人口状态
    add_time DATETIME           -- 添加时间
);

CREATE TABLE ZD_CASE_RYLX ( -- 人员类型字典
    ID TEXT, -- 主键
    DM TEXT, -- 代码
    MC TEXT, -- 名称
    PYM TEXT, -- 拼音码
    ADDDATETIME DATETIME, -- 添加时间
    ISDEL TEXT, -- 是否删除
    JP TEXT, -- 简拼
    ORDER_ID INTEGER, -- 排序
    PRIMARY KEY (ID)
);

CREATE TABLE ZD_CASE_TSRYLX ( -- 特殊人员类型字典
    ID TEXT, -- 主键
    DM TEXT, -- 代码
    MC TEXT, -- 名称
    PYM TEXT, -- 拼音码
    ADDDATETIME DATETIME, -- 添加时间
    ISDEL TEXT, -- 是否删除
    JP TEXT, -- 简拼
    ORDER_ID INTEGER, -- 排序
    PRIMARY KEY (ID)
);

CREATE TABLE ZD_CASE_XZQH ( -- 行政区划字典
    ID TEXT, -- 主键
    DM TEXT, -- 代码
    MC TEXT, -- 名称
    PYM TEXT, -- 拼音码
    ADDDATETIME DATETIME, -- 添加时间
    ISDEL TEXT, -- 是否删除
    JP TEXT, -- 简拼
    ORDER_ID INTEGER, -- 排序
    PRIMARY KEY (ID)
);

CREATE TABLE ZD_CASE_JZLB ( -- 警种列表字典
    ID TEXT, -- 主键
    DM TEXT, -- 代码
    MC TEXT, -- 名称
    PYM TEXT, -- 拼音码
    ADDDATETIME DATETIME, -- 添加时间
    ISDEL TEXT, -- 是否删除
    JP TEXT, -- 简拼
    ORDER_ID INTEGER, -- 排序
    PRIMARY KEY (ID)
);

CREATE TABLE ZD_CASE_AJZT ( -- 案件状态字典
    ID TEXT, -- 主键
    DM TEXT, -- 代码
    MC TEXT, -- 名称
    PYM TEXT, -- 拼音码
    ADDDATETIME DATETIME, -- 添加时间
    ISDEL TEXT, -- 是否删除
    JP TEXT, -- 简拼
    ORDER_ID INTEGER, -- 排序
    PRIMARY KEY (ID)
);

CREATE TABLE ZD_CASE_AJLY ( -- 案件来源字典
    ID TEXT, -- 主键
    DM TEXT, -- 代码
    MC TEXT, -- 名称
    PYM TEXT, -- 拼音码
    ADDDATETIME DATETIME, -- 添加时间
    ISDEL TEXT, -- 是否删除
    JP TEXT, -- 简拼
    ORDER_ID INTEGER, -- 排序
    PRIMARY KEY (ID)
);

CREATE TABLE ZD_CASE_JDZT ( -- 监督状态字典
    ID TEXT, -- 主键
    DM TEXT, -- 代码
    MC TEXT, -- 名称
    PYM TEXT, -- 拼音码
    ADDDATETIME DATETIME, -- 添加时间
    ISDEL TEXT, -- 是否删除
    JP TEXT, -- 简拼
    ORDER_ID INTEGER, -- 排序
    PRIMARY KEY (ID)
);

CREATE TABLE ZD_CASE_BJLBDMB ( -- 报警类别字典
    ID TEXT, -- 主键
    DM TEXT, -- 代码
    MC TEXT, -- 名称
    PYM TEXT, -- 拼音码
    ADDDATETIME DATETIME, -- 添加时间
    ISDEL TEXT, -- 是否删除
    JP TEXT, -- 简拼
    ORDER_ID INTEGER, -- 排序
    PRIMARY KEY (ID)
);

CREATE TABLE ZD_CASE_JQFPJG ( -- 警情分批结果类型字典
    ID TEXT, -- 主键
    DM TEXT, -- 代码
    MC TEXT, -- 名称
    PYM TEXT, -- 拼音码
    ADDDATETIME DATETIME, -- 添加时间
    ISDEL TEXT, -- 是否删除
    JP TEXT, -- 简拼
    ORDER_ID INTEGER, -- 排序
    PRIMARY KEY (ID)
);

CREATE TABLE ZD_CASE_ZABLX ( -- 专案包类型字典
    ID TEXT, -- 主键
    DM TEXT, -- 代码
    MC TEXT, -- 名称
    PYM TEXT, -- 拼音码
    ADDDATETIME DATETIME, -- 添加时间
    ISDEL TEXT, -- 是否删除
    JP TEXT, -- 简拼
    ORDER_ID INTEGER, -- 排序
    PRIMARY KEY (ID)
);

CREATE TABLE ZD_CASE_DZLX ( -- 电信诈骗案件类型
    ID TEXT, -- 主键
    DM TEXT, -- 代码
    MC TEXT, -- 名称
    PYM TEXT, -- 拼音码
    ADDDATETIME DATETIME, -- 添加时间
    ISDEL TEXT, -- 是否删除
    JP TEXT, -- 简拼
    ORDER_ID INTEGER, -- 排序
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_AQ_ZJCL ( -- 案件安全证据材料
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    JQBH TEXT, -- 警情编号
    CLMC TEXT, -- 材料名称
    CLLX TEXT, -- 材料类型
    RYBH TEXT, -- 材料相关人
    RYXM TEXT, -- 材料相关人姓名
    SCSJ DATETIME, -- 上传时间
    CBDW_BH TEXT, -- 承办单位
    CBDW_MC TEXT, -- 承办单位名称
    CBQY_BH TEXT, -- 承办区域
    SIGNNAME TEXT, -- 公章名称（用于打印公章）
    CLLX_ID TEXT, -- 材料类型ID
    PSIGNNAME TEXT, -- 公章落款（用于打印公章落款）
    BGLYY TEXT, -- 不关联原因
    JBR_XM TEXT, -- 经办人姓名
    JBR_SFZH TEXT, -- 经办人身份证号
    WSH TEXT, -- 文书号
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_FW_AY ( -- 法务案件案由
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    BH TEXT, -- 案由(案别)编号
    MC TEXT, -- 案由(案别)名称
    SJBH TEXT, -- 上级案由（案别）编号
    XYNR1 TEXT, -- 需要内容1
    ZHNR1 TEXT, -- 组合内容1
    XYNR2 TEXT, -- 需要内容2
    ZHNR2 TEXT, -- 组合内容2
    XYNR3 TEXT, -- 需要内容3
    ZHNR3 TEXT, -- 组合内容3
    XYNR4 TEXT, -- 需要内容4
    ZHNR4 TEXT, -- 组合内容4
    XYNR5 TEXT, -- 需要内容5
    ZHNR5 TEXT, -- 组合内容5
    XYNR6 TEXT, -- 需要内容6
    ZHNR6 TEXT, -- 组合内容6
    SFYZJD INTEGER, -- 是否叶子节点
    IS_ZDY INTEGER, -- 是否自定义案别
    QY_BH TEXT, -- 自定义案由所属区域编号
    QP TEXT, -- 全拼
    JP TEXT, -- 简拼
    SFZFAY INTEGER, -- 是否作废案由
    PID TEXT, -- 上级ID
    DYGC TEXT, -- 犯罪构成
    FXKZ TEXT, -- 风险控制
    SFYTHCJ INTEGER, -- 是否一体化采集
    SSAJLB TEXT, -- 案件类别
    AYLB TEXT, -- 案由类别
    TKX_ID TEXT, -- 法律条款项ID
    SFAYLB INTEGER, -- 是否案由类别
    FLFG_TKX_QC TEXT, -- 法律款项全称
    FLFG_TKX_FLNR TEXT, -- 法律内容
    CLBZ TEXT, -- 裁量标准
    JLTS_SX INTEGER, -- 拘留天数上限
    JLTS_XX INTEGER, -- 拘留天数下限
    FKJE_SX INTEGER, -- 罚款金额上限
    FKJE_XX INTEGER, -- 罚款金额下限
    ZM_BH TEXT, -- 罪名编号
    ZM_MC TEXT, -- 罪名名称
    FKJE_SX_DW INTEGER, -- 罚款金额上限(单位)
    FKJE_XX_DW INTEGER, -- 罚款金额下限(单位)
    AYBH TEXT, -- 案由编号
    JZLB TEXT, -- 警种类别zd_case_jzlb
    TJBH TEXT, -- 统计编号
    TJMC TEXT, -- 统计名称
    TIPS TEXT, -- 负面清单选择提示
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_GG_AJAB ( -- 案件案编信息
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    AJBH TEXT, -- 案件编号
    AYBH TEXT, -- 罪名编号
    AYMC TEXT, -- 罪名名称
    IS_HISTORY TEXT, -- 是否历史案由
    CBDW_BH TEXT, -- 承办单位编号
    CBQY_BH TEXT, -- 承办区域编号
    ABXL1 TEXT, -- 案由编号1
    ABXL1_NAME TEXT, -- 案由名称1
    ABXL2 TEXT, -- 案由编号2
    ABXL2_NAME TEXT, -- 案由名称2
    ABXL3 TEXT, -- 案由编号3
    ABXL3_NAME TEXT, -- 案由名称3
    ABXLMX TEXT, -- 案由明细编号
    ABXLMX_NAME TEXT, -- 案由明细名称
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_GG_AJBL ( -- 案件办理信息
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    AJBH TEXT, -- 案件编号
    LB TEXT, -- 类别
    CBR_SFZH TEXT, -- 办案民警身份证号码
    CBDW_BH TEXT, -- 办案单位编号
    CBQY_BH TEXT, -- 区域
    BGYY TEXT, -- 变更原因
    BGSJ DATETIME, -- 变更时间
    FPR TEXT, -- 分配人
    CBDW_MC TEXT, -- 承办单位名称
    CBQY_JC TEXT, -- 承办区域简称
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_GG_AJXX ( -- 案件基本信息
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    AJBH TEXT, -- 案件编号
    AJMC TEXT, -- 案件名称
    JYAQ TEXT, -- 简要案情
    AJLX TEXT, -- 案件类型
    ZBDWJZ TEXT, -- 主办单位警种
    AJZT TEXT, -- 案件状态
    CBDW_BH TEXT, -- 承办单位（主办）
    CBQY_BH TEXT, -- 承办单位区域
    FADD TEXT, -- 发案地点
    SLSJ DATETIME, -- 受理时间
    LASJ DATETIME, -- 受/立案时间
    JASJ DATETIME, -- 结案时间
    CFSJ DATETIME, -- 处罚时间
    FASJ DATETIME, -- 发案时间
    SLDW_BH TEXT, -- 受理单位编号
    SLDW_MC TEXT, -- 受理单位名称
    TJSJ DATETIME, -- 调解时间
    SSSJ DATETIME, -- 起诉时间
    ZBR_SFZH TEXT, -- 主办人身份证号
    ZBR_XM TEXT, -- 主办人姓名
    CBDW_MC TEXT, -- 主办单位名称
    CBQY_JC TEXT, -- 主办单位区域
    IS_SW TEXT, -- 是否涉外
    IS_TJ TEXT, -- 是否现场调解案件
    JQBH TEXT, -- 警情编号
    XYR_XM TEXT, -- 嫌疑人姓名
    AJLY TEXT, -- 案件来源
    JDZT TEXT, -- 监督状态
    AJDF INTEGER, -- 案件得分
    FXDJ INTEGER, -- 风险等级
    ZBX TEXT, -- 横坐标
    ZBY TEXT, -- 纵坐标
    SARY_XM TEXT, -- 涉案人员姓名
    SFBPAJ TEXT, -- 是否必评案件
    AJJF INTEGER, -- 案件积分
    SFGK TEXT, -- 是否公开
    GKFQR_XM TEXT, -- 公开发起人姓名
    GKFQR_SFZH TEXT, -- 公开发起人身份证号
    GKFQSJ DATETIME, -- 公开发起时间
    GKSPR_XM TEXT, -- 公开审批人姓名
    GKSPR_SFZH TEXT, -- 公开审批人身份证号
    BGKLY TEXT, -- 不公开理由
    GKSPSJ DATETIME, -- 公开审批时间
    SPYJ TEXT, -- 审批意见
    GKZT TEXT, -- 公开状态
    ZHLAYY TEXT, -- 暂缓立案原因
    KYJSSJ DATETIME, -- 勘验结束时间
    AJLB TEXT, -- 案件类别
    FASJ1 DATETIME, -- 作案时间上限
    FASJ2 DATETIME, -- 作案时间下限
    ZABS TEXT, -- 专案标识
    PXJARQ DATETIME, -- 破销结案日期
    PXJABS TEXT, -- 案件状态标识
    ZASDTDMS TEXT, -- 作案手段描述
    XZCS TEXT, -- 选择处所
    XZDX TEXT, -- 选择对象
    XZWP TEXT, -- 选择物品
    SFSJ TEXT, -- 是否涉警
    ABXL1 TEXT, -- 一级案件类别编号
    ABXL1_NAME TEXT, -- 一级案件类别名称
    ABXL2 TEXT, -- 二级案件类别编号
    ABXL2_NAME TEXT, -- 二级案件类别名称
    ABXL3 TEXT, -- 三级案件类别编号
    ABXL3_NAME TEXT, -- 三级案件类别名称
    PHAJS INTEGER, -- 破获案件起数
    IS_YSSHSE TEXT, -- 是否疑似涉黑涉恶
    PXSJ DATETIME, -- 排序时间,用于列表排序
    SSYJ TEXT, -- 三色预警
    JTWFBH TEXT, -- 交通违法编号
    JTWFBH_GLSJ DATETIME, -- 交通违法关联时间
    YSZT TEXT, -- 案件移送状态
    YSYSZT TEXT, -- 预审移送状态
    YSZBMJ_SFZH TEXT, -- 预审主办民警身份证号
    YSXBMJ_SFZH TEXT, -- 预审协办民警身份证号
    YSZBMJ_XM TEXT, -- 预审主办民警姓名
    YSXBMJ_XM TEXT, -- 预审协办民警姓名
    JSYJ TEXT, -- 接送意见
    BZDZK TEXT, -- 标准地址库
    SSJQDM TEXT, -- 所属警区代码
    SFSM TEXT, -- 是否涉密
    SMGKZT TEXT, -- 涉密公开状态
    QTCLSM TEXT, -- 其他处理说明
    BZ TEXT, -- 备注
    SMJB TEXT, -- 涉密级别
    ZBBJ TEXT, -- 在办办结
    SMZT TEXT, -- 涉密状态
    SMLY TEXT, -- 涉密理由
    SMFQR_XM TEXT, -- 涉密发起人姓名
    SMFQR_SFZH TEXT, -- 涉密发起人身份证号
    SFYSASP INTEGER, -- 是否有涉案视频
    ISAGREEJOIN INTEGER, -- 是否同意参与
    NOAGREEREASON TEXT, -- 不同意参与原因
    XZDQZQZBR_SFZH TEXT, -- 协助调取证据主办人身份证号
    XZDQZQXBR_SFZH TEXT, -- 协助调取证据协办人身份证号
    ISFC TEXT, -- 是否封存
    JCKSBLYY TEXT, -- 解除快速办理原因
    JCKSBLSJ DATETIME, -- 解除快速办理时间
    KSBLLX TEXT, -- 快速办理类型
    SFZJ INTEGER, -- 是否（快速办理）自建案件
    ZKSBL_SJ DATETIME, -- 转快速办理时间
    SMCKRYBGZT TEXT, -- 涉密查看人员变更变更状态
    KSBL TEXT, -- 是否快速办理案件
    YJYS TEXT, -- 移交移送标记
    XZQY TEXT, -- 行政区域
    BZDZ TEXT, -- 标准地址
    BZDZBH TEXT, -- 标准地址编号
    BCSM TEXT, -- 补充说明
    XZQYBH TEXT, -- 行政区域编号
    ZMWFXW TEXT, -- 罪名或违法行为
    BYCFSJ DATETIME, -- 不予处罚时间
    ZZDCSJ DATETIME, -- 终止调查时间
    BYLASJ DATETIME, -- 不予立案时间
    BJAJBM TEXT, -- 部级案件编码
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_GG_AJ_KZXX ( -- 案件扩展信息
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    AJBH TEXT, -- 案件编号
    AJLX TEXT, -- 案件类型
    FAQX TEXT, -- 发案区县
    JDCLG TEXT, -- 街道村路巷
    SSJQ TEXT, -- 所属警区
    SSSQ TEXT, -- 所属社区
    FACS TEXT, -- 发案场所
    FADY TEXT, -- 发案地域
    SR INTEGER, -- 伤人（数量）
    SSJE INTEGER, -- 损失金额（元）
    ZABS TEXT, -- 专案标识
    ZJ TEXT, -- 证据（多选）
    SFSW TEXT, -- 是否涉外
    LXFS TEXT, -- 联系方式
    FXXS TEXT, -- 发现形式
    WHCD TEXT, -- 危害程度
    BLYY TEXT, -- 补立原因
    ZAZT TEXT, -- 作案状态
    XZBL TEXT, -- 协助办理
    DBJB TEXT, -- 督办级别
    BMJB TEXT, -- 保密级别
    ZABH TEXT, -- 主案编号
    FZZT TEXT, -- 犯罪主体
    GJ TEXT, -- 国家
    SCJG TEXT, -- 审查结果
    BLAJ TEXT, -- 是否补立案件
    SFNWGJ TEXT, -- 是否内外勾结
    GJDX TEXT, -- 所勾结对象
    CAYY TEXT, -- 撤案原因
    PAFS TEXT, -- 破案方式
    FZJT TEXT, -- 犯罪集团类别
    XCKY TEXT, -- 现场勘验
    XZSJ TEXT, -- 选择时机（多选）
    XZBW TEXT, -- 选择部位（多选）
    ZAGJ TEXT, -- 作案工具（多选）
    XZDX TEXT, -- 选择对象（多选）
    ZARS INTEGER, -- 作案人数
    ZASD TEXT, -- 作案手段
    ZATD TEXT, -- 作案特点
    ZAXS TEXT, -- 作案形式
    SHR INTEGER, -- 死（人）
    WHSS INTEGER, -- 挽回损失（元）
    SAJZ INTEGER, -- 涉案价值（元）
    PASJ DATETIME, -- 破案时间
    XASJ DATETIME, -- 销案时间
    YCSJ DATETIME, -- 移送（移出）时间
    YSSASJ DATETIME, -- 预审受案时间
    THSJ DATETIME, -- 退回原单位处理时间
    YSQSSJ DATETIME, -- 移送起诉时间
    YSSJ DATETIME, -- 一审时间
    ESSJ DATETIME, -- 二审时间
    FADPCS TEXT, -- 发案地派出所
    JCSJ DATETIME, -- 拘传时间
    JLSJ DATETIME, -- 拘留时间
    QBSJ DATETIME, -- 取保时间
    JJSJ DATETIME, -- 监居时间
    TBSJ DATETIME, -- 提捕时间
    DBSJ DATETIME, -- 逮捕时间
    PJQK TEXT, -- 判决情况
    CBDW_BH TEXT, -- 承办单位编号
    CBQY_BH TEXT, -- 承办区域编号
    FASJ1 DATETIME, -- 作案时间上限 年月日时分
    FASJ2 DATETIME, -- 作案时间下限 年月日时分
    FXSJ DATETIME, -- 发现时间
    XZCS TEXT, -- 选择处所（多选）
    SFSJ TEXT, -- 是否涉警
    XZAB TEXT, -- 刑侦案别
    SQBH TEXT, -- 社区编号
    YWXGSPJK TEXT, -- 有无相关视频监控
    SFTGWX TEXT, -- 是否通过微信联系
    SFTGQQ TEXT, -- 是否通过QQ联系
    YWXYR TEXT, -- 有无嫌疑人信息
    YWYHKH TEXT, -- 案情有无银行卡号
    YWZFBZH TEXT, -- 案情有无支付宝账号
    SFSJQTWLSF TEXT, -- 案情是否涉及其他网络身份信息
    DSRSFRS TEXT, -- 当事人之间是否认识
    YWZRMJZ TEXT, -- 有无证人或目击者
    YWDNA TEXT, -- 有无证DNA证据
    YWXGSPJKVAL TEXT, -- 相关视频监控
    SFTGWXVAL TEXT, -- 微信号
    SFTGQQVAL TEXT, -- QQ号
    YWXYRVAL TEXT, -- 嫌疑人信息
    YWYHKHVAL TEXT, -- 银行卡号
    YWZFBZHVAL TEXT, -- 支付宝账号
    SFSJQTWLSFVAL TEXT, -- 其他网络身份信息
    DSRSFRSVAL TEXT, -- 和当事人的关系
    YWZRMJZVAL TEXT, -- 目击证人或目击者信息
    YWDNAVAL TEXT, -- DNA证据
    SFSY TEXT, -- 是否属"扰乱疫情防控秩序"案件
    SFFF TEXT, -- 是否属非访案件
    HOAJ TEXT, -- 是否为互殴案件
    ZDFWQJ TEXT, -- 是否存在正当防卫情节
    SFJCF TEXT, -- 是否双方均处罚
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_GG_JQXX ( -- 警情信息
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    JQBH TEXT, -- 警情编号
    BJSJ DATETIME, -- 报警时间
    BJFS TEXT, -- 报警方式
    BJRXM TEXT, -- 报警人
    BJRXB TEXT, -- 报警人性别
    BJRLXDH TEXT, -- 报警人联系电话
    BJRGZDW TEXT, -- 报警人工作单位
    BJRZZ TEXT, -- 报警人住址
    BJLB TEXT, -- 报警类别
    BJNR TEXT, -- 报警内容
    AFSJ DATETIME, -- 案发时间
    AFDD TEXT, -- 案发地点
    GXDWBH TEXT, -- 管辖单位代码
    GXDWMC TEXT, -- 管辖单位名称
    CJNR TEXT, -- 处警意见
    CJR_SFZH TEXT, -- 处警人身份证号码
    CJR_XM TEXT, -- 处警人姓名
    CJDW TEXT, -- 处警单位
    CBQY_BH TEXT, -- 区域编号
    DJSJ DATETIME, -- 登记时间
    FPJG TEXT, -- 领导分流结果
    SPR_SFZH TEXT, -- 分配领导身份证号
    SPR_XM TEXT, -- 分配领导姓名
    SPSJ DATETIME, -- 分配时间
    AJBH TEXT, -- 案件编号
    IS_CFJQ TEXT, -- 是否重复警情
    GLJQBH TEXT, -- 关联警情编号
    JQZT TEXT, -- 警情状态
    IS_XCTJAJ TEXT, -- 是否现场调解案件
    IS_ZDJQ TEXT, -- 是否重大警情
    IS_ZG TEXT, -- 是否整改
    IS_WTJQ TEXT, -- 是否问题警情
    ZBR_SFZH TEXT, -- 主办人身份证号
    ZBR_XM TEXT, -- 主办人姓名
    XBR_SFZH TEXT, -- 协办人身份证号
    XBR_XM TEXT, -- 协办人姓名
    YSJSDWBH TEXT, -- 移送接收单位编号
    YSJSDWMC TEXT, -- 移送接收单位名称
    YSJSR_SFZH TEXT, -- 移送接收人身份证号码
    YSJSR_XM TEXT, -- 移送接收人姓名
    ZBX TEXT, -- 坐标X
    ZBY TEXT, -- 坐标Y
    IS_YSSHSE TEXT, -- 是否涉黑涉恶
    SFGK TEXT, -- 是否公开
    BGKYY TEXT, -- 不公开原因
    SFJD TEXT, -- 是否监督
    SFYNFZ TEXT, -- 是否疑难复杂
    ECFLYY TEXT, -- 二次分流原因
    BZJQXZDM TEXT, -- 标准警情性质代码
    BZJQXZMC TEXT, -- 标准警情性质名称
    NBYSJQXZDM TEXT, -- 内部原始警情性质代码
    NBYSJQXZMC TEXT, -- 内部原始警情性质名称
    NBQRYSJQXZDM TEXT, -- 内部确认原始警情性质代码
    NBQRYSJQXZMC TEXT, -- 内部确认原始警情性质名称
    NBQRJQXZDM TEXT, -- 警情性质代码
    NBQRJQXZMC TEXT, -- 警情性质名称
    FACSDM TEXT, -- 发案场所代码
    FACSMC TEXT, -- 发案场所名称
    QX TEXT, -- 区县
    JD TEXT, -- 街道
    XXDZ TEXT, -- 详细地址
    SSSQ TEXT, -- 所属社区
    SSJQ TEXT, -- 所属警区
    QXDM TEXT, -- 区县代码
    JDDM TEXT, -- 街道代码
    SSSQDM TEXT, -- 所属社区代码
    SSJQDM TEXT, -- 所属警区代码
    QSZT TEXT, -- 签收状态
    BQSYY TEXT, -- 不签收原因
    QSRSFZH TEXT, -- 签收人身份证号
    QSSJ DATETIME, -- 签收时间
    BZDZK TEXT, -- 标准地址库
    QTCLSM TEXT, -- 其他处理说明
    SFSM TEXT, -- 是否涉密
    SMGKZT TEXT, -- 涉密公开状态
    ZJQBH TEXT, -- 主警情编号
    LXDH TEXT, -- 联系电话
    PCJYBH TEXT, -- 派出警员编号
    PCJYXM TEXT, -- 派出警员姓名
    BZ TEXT, -- 备注
    DCJGMC TEXT, -- 督察结果名称
    DCJGDM TEXT, -- 督察结果代码
    CJQK TEXT, -- 处警情况
    FLR_SFZH TEXT, -- 分类人身份证号
    FLR_XM TEXT, -- 分类人姓名
    FLSJ DATETIME, -- 分类时间
    ZABLX TEXT, -- 专案包类型
    RBR_SFZH TEXT, -- 入包人身份证号
    RBR_XM TEXT, -- 入包人姓名
    RBSJ DATETIME, -- 入包时间
    TSSJ DATETIME, -- 推送时间
    DZAJLX TEXT, -- 电诈案件类型
    ZBZCY_SFZH TEXT, -- 主办侦查员身份证号
    ZBZCY_XM TEXT, -- 主办侦查员姓名
    XBZCY_SFZH TEXT, -- 协办侦查员身份证号
    XBZCY_XM TEXT, -- 协办侦查员姓名
    ZABBH TEXT, -- 专案包编号
    SFBJ INTEGER, -- 是否办结
    SMJB TEXT, -- 涉密级别
    SMZT TEXT, -- 涉密状态
    SMLY TEXT, -- 涉密理由
    SMFQR_XM TEXT, -- 涉密发起人姓名
    SMFQR_SFZH TEXT, -- 涉密发起人身份证号
    SFSJWCNR TEXT, -- 是否涉及未成年人
    FPJG_ST TEXT, -- 领导分流结果
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_GG_JQXX_FLJL ( -- 警情分流记录
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    JQBH TEXT, -- 警情编号
    FPJG TEXT, -- 领导分流结果
    SPR_SFZH TEXT, -- 审批人身份证号
    SPR_XM TEXT, -- 审批人姓名
    SPSJ DATETIME, -- 审批人时间
    FLCS TEXT, -- 第几次审批
    JQID TEXT, -- 警情ID
    FLDWBH TEXT, -- 分流单位编号
    CZPT INTEGER, -- 操作平台
    FKID TEXT, -- 反馈ID
    YSJSDWBH TEXT, -- 移送接收单位编号
    YSJSDWMC TEXT, -- 移送接收单位名称
    YSJSR_SFZH TEXT, -- 移送接收人身份证号码
    YSJSR_XM TEXT, -- 移送接收人姓名
    FLLX INTEGER, -- 分流类型
    SZRYSFZD INTEGER, -- 失踪人员是否找到
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_GG_SADWXX ( -- 涉案单位信息
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    DWBH TEXT, -- 单位编号
    DWMC TEXT, -- 单位名称
    LXFS TEXT, -- 联系方式
    DWLX TEXT, -- 单位类型
    BASJ DATETIME, -- 报案时间
    LXRXB TEXT, -- 联系人性别
    DWDZ TEXT, -- 地址
    CBDW_BH TEXT, -- 承办单位编号
    CBQY_BH TEXT, -- 承办区域编号
    AJBH TEXT, -- 案件编号
    SSJE TEXT, -- 损失金额
    YSSJ DATETIME, -- 移送时间
    LXR TEXT, -- 联系人
    ZCDZ TEXT, -- 注册地址
    BGDZ TEXT, -- 办公地址
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_GG_SARYXX ( -- 涉案人员信息
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    RYBH TEXT, -- 人员编号
    XM TEXT, -- 人员姓名
    ZJLX TEXT, -- 证件类型
    SFZH TEXT, -- 证件号码
    XB TEXT, -- 性别
    MZ TEXT, -- 民族
    CSRQ DATETIME, -- 出生日期
    NL INTEGER, -- 年龄(下限)
    LXFS TEXT, -- 联系方式
    QTLXFS TEXT, -- 更多联系方式
    RYLX TEXT, -- 人员类型
    SFTSQT TEXT, -- 是否特殊群体
    TSQT TEXT, -- 特殊群体
    BASJ DATETIME, -- 报案时间
    BAFS TEXT, -- 报案方式
    SFQZ TEXT, -- 是否取证
    SSQK TEXT, -- 伤势情况
    CWSS TEXT, -- 财物损失
    TSRYLX TEXT, -- 特殊人员类型
    BGXX TEXT, -- 报告信息
    CFXX TEXT, -- 处罚信息
    GZDW TEXT, -- 工作单位
    HJD TEXT, -- 户籍地
    HJDXZ TEXT, -- 户籍地详址
    XZD TEXT, -- 现住地
    XZDXZ TEXT, -- 现住地详址
    CYM TEXT, -- 曾用名
    BDBR_BH TEXT, -- 被担保人编号
    BDBR TEXT, -- 被担保人
    YBDBRGX TEXT, -- 与被担保人关系
    LSSWS TEXT, -- 律师事务所
    LXDH TEXT, -- 联系电话
    BBHR_BH TEXT, -- 被辩护人编号
    BBHR TEXT, -- 被辩护人
    WTSJ DATETIME, -- 委托时间
    HJSJ DATETIME, -- 会见时间
    HJJL TEXT, -- 会见记录
    SFXK TEXT, -- 是否许可
    SF TEXT, -- 身份
    GJ TEXT, -- 国籍
    TBSJ DATETIME, -- 同步时间
    SFBMSF TEXT, -- 是否保密身份
    SHLB TEXT, -- 损害类别
    SHFD TEXT, -- 损害幅度
    CCSSFD TEXT, -- 财产损失幅度
    WTR TEXT, -- 委托人
    LSZYZBH TEXT, -- 律师执业证编号
    NLSX INTEGER, -- 年龄(上限)
    ZY TEXT, -- 职业
    ZPID TEXT, -- 照片ID
    SFZBM INTEGER, -- 是否自报名
    BM TEXT, -- 别名
    CH TEXT, -- 绰号
    ZZMM TEXT, -- 政治面貌
    WHCD TEXT, -- 文化程度
    CBDW_BH TEXT, -- 承办单位编号
    CBQY_BH TEXT, -- 承办区域编号
    ISGZRY TEXT, -- 是否公职人员
    GZRY TEXT, -- 何种公职人员
    YWX TEXT, -- 英文姓
    YWM TEXT, -- 英文名
    RDSJ DATETIME, -- 入党时间
    SZDZB TEXT, -- 所在党支部
    RDJB TEXT, -- 人大级别
    SZSSRD TEXT, -- 所在省市（人大）
    ZXJB TEXT, -- 政协级别
    SZSSZX TEXT, -- 所在省市（政协）
    SFDY TEXT, -- 是否党员
    RDDB TEXT, -- 是否人大代表
    ZXWY TEXT, -- 是否政协委员
    ZFZH TEXT, -- 支付账号
    YXZH TEXT, -- 游戏账号
    YXYRGX TEXT, -- 与嫌疑人关系
    CFSJ DATETIME, -- 处罚时间
    CFCS TEXT, -- 处罚措施
    CFJE TEXT, -- 处罚金额 单位：元
    SFDA TEXT, -- 是否到案
    GASJ DATETIME, -- 归案时间
    SFWCNR TEXT, -- 是否未成年人
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_GG_SARY_KZXX ( -- 涉案人员扩展信息
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    RYBH TEXT, -- 人员编号
    XM TEXT, -- 人员姓名
    HJQH TEXT, -- 户籍区划
    XZDQH TEXT, -- 现住地区划
    SWQK TEXT, -- 伤亡情况
    ZHLX TEXT, -- 账户类型
    YHZH TEXT, -- 银行账号
    KHMC TEXT, -- 开户名称
    KHYH TEXT, -- 开户银行
    JYSM TEXT, -- 简要说明
    GJ TEXT, -- 国籍地区
    YWX TEXT, -- 英文姓
    YWM TEXT, -- 英文名
    ZJBZDD TEXT, -- 证件标注地址
    ZJLX TEXT, -- 证件类型
    ZJHM TEXT, -- 证件号码
    FZJG TEXT, -- 发证机关
    QTZJZL TEXT, -- 其它证件总类
    YWZJMC TEXT, -- 境外证件名称
    ZJYXQZSJ TEXT, -- 证件有效起止时间
    BMJB TEXT, -- 保密级别
    TLQXRQ DATETIME, -- 停留期限日期
    TLTS INTEGER, -- 停留天数
    BZ TEXT, -- 备注
    CBDW_BH TEXT, -- 承办单位编号
    CBQY_BH TEXT, -- 承办区域编号
    SAZZ TEXT, -- 涉案总值
    SSJE TEXT, -- 损失金额
    WHSSJE TEXT, -- 挽回损失金额
    HYZK TEXT, -- 婚姻状况
    HJDQHBH TEXT, -- 户籍地区划
    XZDQHBH TEXT, -- 现住地区划
    ZY TEXT, -- 职业
    SPQD TEXT, -- 受骗渠道
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_GG_WPXX ( -- 物品信息
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    WPBH TEXT, -- 物品编号
    CLLX TEXT, -- 处理类型
    LX TEXT, -- 物品类型（随身物品、涉案物品）
    MC TEXT, -- 物品名称
    LB TEXT, -- 物品类别（交通工具类）
    CYR TEXT, -- 持有人
    DW TEXT, -- 物品单位
    SL INTEGER, -- 物品数量
    TZ TEXT, -- 物品特征
    CFWZ TEXT, -- 存放位置
    TXM TEXT, -- 条行编码
    BZ TEXT, -- 备注
    WPZT TEXT, -- 物品状态
    CBR_SFZH TEXT, -- 主办民警身份证号码
    CBDW_BH TEXT, -- 承办单位（主办）
    CBDW_JC TEXT, -- 承办单位简称
    CBQY_BH TEXT, -- 承办单位区域
    EWM TEXT, -- 二维码
    JZ INTEGER, -- 价值
    CCLX TEXT, -- 车船/船舶类型
    CCXH TEXT, -- 型号/船籍港
    CCPH TEXT, -- 车牌号/船名号
    CCYS TEXT, -- 车船颜色
    TXGJPP TEXT, -- 通讯工具品牌
    TXGJXH TEXT, -- 通讯工具型号
    TXGJYS TEXT, -- 通讯工具颜色
    ZJRYXM TEXT, -- 证件人员姓名
    ZJHM TEXT, -- 证件号码
    JYDQPP TEXT, -- 通讯工具品牌
    JYDQXH TEXT, -- 家用电器型号
    QX TEXT, -- 枪型
    ZDZL TEXT, -- 子弹种类
    WPCLQK TEXT, -- 物品处理情况
    RKSJ DATETIME, -- 入库时间
    CKSJ DATETIME, -- 出库时间
    RKMJ_SFZH TEXT, -- 入库民警
    RKMJ_XM TEXT, -- 入库民警姓名
    RKBZ TEXT, -- 入库备注
    CKMJ_SFZH TEXT, -- 出库民警
    CKMJ_XM TEXT, -- 出库民警姓名
    CKMS TEXT, -- 出库描述
    JSMJ_SFZH TEXT, -- 接收民警
    JSMJ_XM TEXT, -- 接收民警姓名
    CFWZMC TEXT, -- 存放位置(名称)
    CKSQR_SFZH TEXT, -- 出库申请人
    CKSQR_XM TEXT, -- 出库申请人姓名
    TBSJ DATETIME, -- 同步时间
    PKLX TEXT, -- 盘库类型
    ZPSFTS INTEGER, -- 照片是否同上
    DCLWPZT TEXT, -- 待处理物品状态
    SJZT TEXT, -- 数据状态
    WPSL TEXT, -- 物品数量（大写）
    SFSY TEXT, -- 是否使用
    XGWPBH TEXT, -- 相关物品编号
    CYR_BH TEXT, -- 持有人编号
    SFHB INTEGER, -- 是否货币
    WPXZ TEXT, -- 物品性质
    ZWPP TEXT, -- 中文品牌
    CLXH TEXT, -- 车辆型号
    CHLLX TEXT, -- 车辆类型
    CLSBDH TEXT, -- 车辆识别代号
    FDJH TEXT, -- 发动机号
    CSYS TEXT, -- 车身颜色
    SSXZ TEXT, -- 使用性质
    CCRQ DATETIME, -- 出厂日期
    QZBFRQ DATETIME, -- 强制报废日期
    JYYXQZ DATETIME, -- 检验有效期止
    BXZZRQ DATETIME, -- 保险终止日期
    JDCZT TEXT, -- 机动车状态
    JDCSYR TEXT, -- 机动车所有人
    CCDJRQ DATETIME, -- 初次登记日期
    DJZS TEXT, -- 登记住所
    LXDH TEXT, -- 联系电话
    GC_JK TEXT, -- 国产/进口
    SGTY TEXT, -- 事故逃逸
    TPC TEXT, -- 套牌车
    DQC TEXT, -- 盗抢车
    HGBZBH TEXT, -- 合格标志编号
    XSZXBH TEXT, -- 行驶证芯编号
    HPZL TEXT, -- 号牌种类
    PC_ID TEXT, -- 批次ID
    SAWPSL TEXT, -- 涉案物品数量
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_GG_WP_KZXX ( -- 物品扩展信息
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    WPBH TEXT, -- 物品编号
    WPXZ TEXT, -- 物品性质
    WPZL TEXT, -- 物品种类
    WPMC TEXT, -- 物品名称
    WPXXMC TEXT, -- 物品详细名称
    SFSA TEXT, -- 是否涉案
    SFWZ TEXT, -- 是否物证
    DW TEXT, -- 单位
    SL INTEGER, -- 数量
    CYR TEXT, -- 持有人
    SZ TEXT, -- 属主
    SZDD TEXT, -- 属主地址
    WPMXFL TEXT, -- 物品明细分类
    WPCFD TEXT, -- 物品存放地
    TZMS TEXT, -- 特征描述
    CBDW_BH TEXT, -- 承办单位编号
    CBQY_BH TEXT, -- 承办区域编号
    SSLX TEXT, -- 损失类型（警综）
    CLLX TEXT, -- 车辆类型（警综）
    SAWPSL TEXT, -- 涉案物品数量
    PRIMARY KEY (ID)
);


CREATE TABLE CASE_GG_XYRYXX ( -- 嫌疑人员信息
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    RYBH TEXT, -- 人员编号
    XM TEXT, -- 人员姓名
    CYM TEXT, -- 曾用名
    BH TEXT, -- 别名
    SFZH TEXT, -- 身份证号码
    QTZJLX1 TEXT, -- 其他证件类型1
    QTZJHM1 TEXT, -- 其他证件号码1
    QTZJLX2 TEXT, -- 其他证件类型2
    QTZJHM2 TEXT, -- 其他证件号码2
    QTZJLX3 TEXT, -- 其他证件类型3
    QTZJHM3 TEXT, -- 其他证件号码3
    XB TEXT, -- 性别
    MZ TEXT, -- 民族
    CSRQ DATETIME, -- 出生日期
    NL INTEGER, -- 年龄(下限)
    LXFS TEXT, -- 联系方式
    QTLXFS TEXT, -- 更多联系方式
    HYZK TEXT, -- 婚姻状况
    ZZMM TEXT, -- 政治面貌
    WHCD TEXT, -- 文化程度
    SG TEXT, -- 身高
    TX TEXT, -- 体型
    ZY TEXT, -- 职业
    ZYLB TEXT, -- 职业类别
    HJD TEXT, -- 户籍地
    HJDXZ TEXT, -- 户籍地详址
    XZD TEXT, -- 现住地
    XZDXZ TEXT, -- 现住地详址
    XZDXZ_X TEXT, -- 现住地坐标X
    XZDXZ_Y TEXT, -- 现住地坐标Y
    GRXG TEXT, -- 个人习惯
    SFTSQT TEXT, -- 是否特殊群体
    TSQT TEXT, -- 特殊群体
    ZW TEXT, -- 指纹
    DNA TEXT, -- DNA
    SFLAR TEXT, -- 是否另案人
    LARSFSFMQ TEXT, -- 另案人身份是否明确
    XX TEXT, -- 血型
    ZAGJ TEXT, -- 作案工具
    ZATD TEXT, -- 作案特点
    JTZK TEXT, -- 家庭状况
    SHGX TEXT, -- 社会关系(简历)
    WFSS TEXT, -- 违法事实
    GJ TEXT, -- 国籍
    GZDW TEXT, -- 工作单位
    BZ TEXT, -- 备注
    SFZBM INTEGER, -- 是否自报名
    DLR TEXT, -- 代理人
    DLRDH TEXT, -- 代理人电话
    SF TEXT, -- 身份
    SFYTHCJ INTEGER, -- 是否一体化采集
    AY_BH TEXT, -- 案由编号
    AY_MC TEXT, -- 案由名称
    TBSJ DATETIME, -- 同步时间
    SFGA TEXT, -- 另案人员是否归案（不是嫌疑人到案标记）
    GASJ DATETIME, -- 归案时间（嫌疑人到案时间）
    SFBMSF TEXT, -- 是否保密身份
    NLSX INTEGER, -- 年龄(上限)
    ZPID TEXT, -- 照片ID
    CRJ_ZJLX TEXT, -- 出入境证件类型
    CRJ_ZJHM TEXT, -- 出入境证件号码
    CH TEXT, -- 绰号
    QKQK TEXT, -- 前科情况
    SFTB INTEGER, -- 是否同步至办案区人员
    SCSPZT TEXT, -- 审批情况
    SFDY TEXT, -- 是否党员
    ZWXX TEXT, -- 指纹信息
    RDDB TEXT, -- 是否人大代表
    ZXWY TEXT, -- 是否政协委员
    CBDW_BH TEXT, -- 承办单位编号
    CBQY_BH TEXT, -- 承办区域编号
    YWJSXX TEXT, -- 有无家属信息
    JZDXZQH TEXT, -- 居住地行政区划代码
    JZDZ TEXT, -- 居住地址
    HJDXZQH TEXT, -- 户籍地行政区划代码
    KY TEXT, -- 口音
    TMTZ TEXT, -- 体貌特征
    TBBJ TEXT, -- 体表标记
    ZC TEXT, -- 专长
    FZJL TEXT, -- 违法犯罪经历
    QZCS TEXT, -- 强制措施
    CSKSSJ TEXT, -- 措施开始时间
    ZSZT TEXT, -- 在所状态
    R_RSSJ DATETIME, -- 入所时间
    C_CSSJ DATETIME, -- 出所时间
    SFDA TEXT, -- 是否到案
    GJGZRY TEXT, -- 是否国家工作人员
    SFBK TEXT, -- 是否边控
    JG TEXT, -- 籍贯
    XZQ TEXT, -- 行政区
    XZQDM TEXT, -- 行政区域编号
    DWRY TEXT, -- 是否单位人员
    GCBH TEXT, -- 过程编号（监管）
    ISXG TEXT, -- 是否可以修改
    XYR_NL TEXT, -- 嫌疑人年龄
    ISGZRY TEXT, -- 是否公职人员
    GZRY TEXT, -- 何种公职人员
    YWX TEXT, -- 英文姓
    YWM TEXT, -- 英文名
    SFXD TEXT, -- 是否涉毒
    XDJYJG TEXT, -- 吸毒检验结果
    BZDZK TEXT, -- 现住标准地址库
    QQ TEXT, -- qq信息
    WX TEXT, -- 微信信息
    ZM TEXT, -- 罪名
    ZMBH TEXT, -- 罪名代码
    ZHDD TEXT, -- 抓获地点
    ZHXZB TEXT, -- 抓获X坐标
    ZHYZB TEXT, -- 抓获Y坐标
    ZHR TEXT, -- 抓获人
    ZHSJ DATETIME, -- 抓获时间
    ZHJG TEXT, -- 抓获经过
    RYZT TEXT, -- 人员状态
    RDSJ DATETIME, -- 入党时间
    SZDZB TEXT, -- 所在党支部
    RDJB TEXT, -- 人大级别
    SZSSRD TEXT, -- 所在省市（人大）
    ZXJB TEXT, -- 政协级别
    SZSSZX TEXT, -- 所在省市（政协）
    ZFZH TEXT, -- 支付宝账户
    YXZH TEXT, -- 游戏账户
    SFGATJM TEXT, -- 是否港澳台居民
    GATSF TEXT, -- 港澳台身份
    MGRY TEXT, -- 敏感人员
    MGRYLX TEXT, -- 敏感人员类型
    ISFC INTEGER, -- 是否封存
    SFYDSP TEXT, -- 是否异地审批
    XMPY TEXT, -- 姓名拼音
    IS_WCN TEXT, -- 发案时是否未成年
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_GG_XYRY_KZXX ( -- 嫌疑人员扩展信息
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    RYBH TEXT, -- 人员编号
    XM TEXT, -- 人员姓名/外国人姓名
    CYM TEXT, -- 曾用名
    RYZT TEXT, -- 人员状态
    RYJS TEXT, -- 人员角色
    ZGBM TEXT, -- 主管部门
    ZTQK TEXT, -- 上网追逃情况
    DNABH TEXT, -- DNA编号
    XTJG TEXT, -- 吸毒检测结果
    BJBKH TEXT, -- 笔记卡编号
    SSSQ TEXT, -- 所属社区
    SFCK TEXT, -- 是否常口
    ZZDPCS TEXT, -- 暂住地派出所
    HJDQH TEXT, -- 户籍地区划
    XJDQH TEXT, -- 现居地区划
    ZZDQH TEXT, -- 暂住地区划
    ZZDDZ TEXT, -- 暂住地地址
    ZY TEXT, -- 职业
    SF TEXT, -- 身份
    HYZK TEXT, -- 婚姻状况
    ZC TEXT, -- 专长
    SFGW TEXT, -- 是否高危人员
    LJD TEXT, -- 落脚点
    JZYY TEXT, -- 居住原由
    GH TEXT, -- 固话
    ZTLX TEXT, -- 在逃类型
    SG1 TEXT, -- 身高1
    SG2 TEXT, -- 身高2
    LX TEXT, -- 脸型
    TX TEXT, -- 体型
    XX TEXT, -- 血型
    TSTZ TEXT, -- 特殊特征
    YCTZ TEXT, -- 牙齿特征
    SWRQ DATETIME, -- 死亡日期
    ZC2 TEXT, -- 足长
    XH TEXT, -- 鞋号
    ZASD TEXT, -- 作案手段
    ZATD TEXT, -- 作案特点
    XZSJ TEXT, -- 选择时机
    XZCS TEXT, -- 选择处所
    ZAGJ TEXT, -- 作案工具
    XZDX TEXT, -- 选择对象
    XZFS TEXT, -- 销赃方式
    ZHFS TEXT, -- 抓获方式
    WFJL TEXT, -- 违法记录
    JL TEXT, -- 简历
    TBR TEXT, -- 填表人
    TBR_BH TEXT, -- 填表人编号
    TBSJ DATETIME, -- 填表时间
    TBDW TEXT, -- 填表单位
    TBDW_BH TEXT, -- 填表单位编号
    KY TEXT, -- 口音
    ZWXX TEXT, -- 指纹信息
    SFGWRY TEXT, -- 是否国家公务人员
    GWRYGZDW TEXT, -- 公务人员工作单位
    CBDW_BH TEXT, -- 承办单位编号
    CBQY_BH TEXT, -- 承办区域编号
    SSJE TEXT, -- 损失金额
    QFQK TEXT, -- 侵犯情况
    SWQK TEXT, -- 伤亡情况
    JSZDABH TEXT, -- 驾驶证档案编号
    ZJCX TEXT, -- 准驾车型
    JSZHM TEXT, -- 驾驶证号
    YXQ_BGN DATETIME, -- 有效期始
    YXQ_END DATETIME, -- 有效期止
    JSZQX TEXT, -- 驾驶证期限
    ZXBH TEXT, -- 证芯编号
    CCLZRQ DATETIME, -- 初次领证日期
    XYTJRQ DATETIME, -- 下一体检日期
    LJJF INTEGER, -- 累积记分
    QFRQ DATETIME, -- 清分日期
    DQZT TEXT, -- 当前状态
    JSRLY TEXT, -- 驾驶人来源
    JXMC TEXT, -- 驾校名称
    SYYXQZ DATETIME, -- 审验有效期止
    FZJG TEXT, -- 发证机关
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_GG_YYWS ( -- 业务文书
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    AJBH TEXT, -- 案件编号
    WSMC TEXT, -- 文书名称
    WSZH TEXT, -- 文书字号
    XGRY_BH TEXT, -- 相关人员编号
    XGRY_XM TEXT, -- 相关人员姓名
    CBR_SFZH TEXT, -- 办案民警
    WSZT TEXT, -- 文书状态
    KJSJ DATETIME, -- 开具时间
    DYCS INTEGER, -- 打印次数
    DYMJ_SFZH TEXT, -- 打印民警
    DYSJ DATETIME, -- 打印时间
    ORDER_ID INTEGER, -- 文书排序
    CBDW_BH TEXT, -- 承办单位编号
    CBDW_MC TEXT, -- 承办单位名称
    BD_ID TEXT, -- 表单ID
    JD_ID TEXT, -- 流程节点ID
    ZJZD TEXT, -- 主键字段
    ZJZ TEXT, -- 主键值
    WSLX_ID TEXT, -- 文书类型ID
    WSLX_MC TEXT, -- 文书类型名称
    SFGLWS INTEGER, -- 是否关联文书
    ZRZ TEXT, -- 责任者
    CBR_XM TEXT, -- 办案民警姓名
    BALCJL_ID TEXT, -- 流程记录ID
    SPR_SFZH TEXT, -- 审批人
    SPR_XM TEXT, -- 审批人姓名
    SPSJ DATETIME, -- 审批时间
    CLDW_BH TEXT, -- 处理单位编号
    CLDW_MC TEXT, -- 处理单位名称
    WS_ID TEXT, -- 文书ID
    WS_BM TEXT, -- 文书表名
    WSLX TEXT, -- 文书类型
    ZFYY TEXT, -- 文书作废原因
    SFJFWS TEXT, -- 是否为检法文书
    SFQMNY INTEGER, -- 是否完成签名捺印
    LINESIZE TEXT, -- 行间距
    SFLTY INTEGER, -- 打印模板类型
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_GG_ZJCL ( -- 证据材料
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    AJBH TEXT, -- 案件编号
    CLMC TEXT, -- 材料名称
    CLLX_ID TEXT, -- 材料类型ID
    KSSJ DATETIME, -- 开始时间
    JSSJ DATETIME, -- 结束时间
    XWR TEXT, -- 询问人
    RYBH TEXT, -- 人员编号
    XM TEXT, -- 被询问人员姓名
    SFZH TEXT, -- 被询问人证件号码
    SFKTCH INTEGER, -- 是否口头传唤
    KTCHSJ DATETIME, -- 口头传唤时间
    KYRY TEXT, -- 勘验人员
    BZ TEXT, -- 备注
    CLLX TEXT, -- 材料类型
    ZPPSR TEXT, -- 照片拍摄人
    ZPPSSJ DATETIME, -- 照片拍摄时间
    ZPPSDD TEXT, -- 照片拍摄地点
    BLLBNAME TEXT, -- 笔录类别
    WPMC TEXT, -- 物品名称
    WPMS TEXT, -- 物品描述
    ZZGC TEXT, -- 制作过程
    YWCFC TEXT, -- 原物存放处
    CYR TEXT, -- 持有人
    ZZR TEXT, -- 制作人
    ZZSJ DATETIME, -- 制作时间
    JDJSSJ DATETIME, -- 鉴定结束时间
    SARY TEXT, -- 涉案人员
    TJSJ DATETIME, -- 调解时间
    FZXYR TEXT, -- 犯罪嫌疑人
    PZSJ DATETIME, -- 批准时间
    PJSJ DATETIME, -- 判决时间
    WSMCNAME TEXT, -- 文书名称
    BARXM TEXT, -- 办案人姓名
    WS_ZJZ TEXT, -- 关联文书ID
    WSZH TEXT, -- 文书字号
    XWR_SFZH TEXT, -- 询问人身份证号
    YQLAQX DATETIME, -- 检察院要求立案期限
    ZJLX_BH TEXT, -- 证据类型编号
    ZJSTBM TEXT, -- 证据视图编码
    ZHSTMC TEXT, -- 证据视图名称
    WPBH TEXT, -- 物品编号
    ZJMCDM TEXT, -- 证据名称代码（刑事案件专用）
    ZJMCXL TEXT, -- 证据名称细类（刑事案件专用）
    ZJTGDXXM TEXT, -- 证据提供对象姓名
    ZJTGDXRYBH TEXT, -- 证据提供对象人员编号
    ZJZMMD TEXT, -- 证据证明目的
    BGLYY TEXT, -- 不关联原因
    SFFY TEXT, -- 是否复议上传
    BCSJ DATETIME, -- 补充时间
    JBR_XM TEXT, -- 经办人姓名
    JBR_SFZH TEXT, -- 经办人身份证号
    JCJG_ID TEXT, -- 检测结果
    JZMLMC TEXT, -- 卷宗目录名称
    JZMLID TEXT, -- 卷宗目录ID
    ZXSJ DATETIME, -- 执行时间 拘留证
    RSSJ DATETIME, -- 入所时间 拘留证
    BSJYY TEXT, -- 不收拘原因
    PRIMARY KEY (ID)
);

CREATE TABLE res_0_clda_jdc (  -- 车辆信息表
    hphm TEXT,                 -- 号牌号码
    hpzl TEXT,                 -- 号牌种类
    hpzl_detail TEXT,          -- 号牌种类详情
    hpys TEXT,                 -- 号牌颜色
    clsbdh TEXT,               -- 车辆识别代号
    syr TEXT,                  -- 机动车所有人
    sfzmhm TEXT,               -- 身份证明号码
    sfzmmc TEXT,               -- 身份证明名称
    sfzmmc_detail TEXT,        -- 身份证明名称详情
    lxdh TEXT,                 -- 联系电话
    zsxxdz TEXT,               -- 住所详细地址
    clpp2 TEXT,                -- 英文品牌
    clpp1 TEXT,                -- 中文品牌
    clxh TEXT,                 -- 车辆型号
    cldl TEXT,                 -- 车辆大类
    cldl_detail TEXT,          -- 车辆大类详情
    cllx TEXT,                 -- 车辆类型
    cllx_detail TEXT,          -- 车辆类型详情
    csys TEXT,                 -- 车身颜色
    csys_detail TEXT,          -- 车身颜色详情
    syxz TEXT,                 -- 使用性质
    syxz_detail TEXT,          -- 使用性质详情
    zt TEXT,                   -- 机动车状态
    ccdjrq TEXT,               -- 初次登记日期
    fprq TEXT,                 -- 发牌日期
    fzrq TEXT,                 -- 发行驶证日期
    syqsrq TEXT,               -- 使用起始日期
    djrq TEXT,                 -- 最近定检日期
    fhgzrq TEXT,               -- 发合格证日期
    yxqz TEXT,                 -- 检验有效期止
    qzbfqz TEXT,               -- 强制报废期止
    bxzzrq TEXT,               -- 保险终止日期
    ccrq TEXT,                 -- 出厂日期
    clyt TEXT,                 -- 车辆用途
    sjhm TEXT,                 -- 手机号码
    clly TEXT,                 -- 1注册2转入3过户
    ncdqsy TEXT,               -- 是否为农村地区使用1-是；2-否
    zzg TEXT,                  -- 制造国
    yxh TEXT,                  -- 原机动车序号
    hdzk TEXT,                 -- 核定载客
    zzl TEXT,                  -- 总质量
    zxxs_detail TEXT,          -- 转向形式详情
    dzyx TEXT,                 -- 电子邮箱
    wxmbc_detail TEXT,         -- 是否为微型面包车详情
    hpzk TEXT,                 -- 驾驶室后排载客人数
    zzz TEXT,                  -- 暂住居住证明
    jbr TEXT,                  -- 经办人
    yqjyqz2 TEXT,              -- 逾期2个检验周期期止
    zsxzqh TEXT,               -- 住所行政区划
    bpcs TEXT,                 -- 补领号牌次数
    cyry TEXT,                 -- 查验人员
    gbthps TEXT,               -- 钢板弹簧片数
    jkpz TEXT,                 -- 进口凭证
    jyhgbzbh TEXT,             -- 检验合格标志
    hmbh TEXT,                 -- 后膜编号
    zzxzqh_detail TEXT,        -- 暂住行政区划详情
    nszmbh TEXT,               -- 纳税证明编号
    zj TEXT,                   -- 轴距
    fzjg TEXT,                 -- 发证机关
    dwbh TEXT,                 -- 单位编号
    zs TEXT,                   -- 轴数
    gcjk TEXT,                 -- 国产/进口
    wxmbc TEXT,                -- 是否为微型面包车1-是；2-否
    sqdm TEXT,                 -- 社区代码
    dybj_detail TEXT,          -- 是否抵押详情
    qmbh TEXT,                 -- 前膜编号
    xgzl TEXT,                 -- 相关资料
    zzg_detail TEXT,           -- 制造国详情
    ltgg TEXT,                 -- 轮胎规格
    xsjg TEXT,                 -- 销售价格
    xsrq TEXT,                 -- 销售日期
    zdjzshs TEXT,              -- 制登记证书行数
    clly_detail TEXT,          -- 车辆来源详情
    bz TEXT,                   -- 备注
    fdjh TEXT,                 -- 发动机号
    zsxzqh_detail TEXT,        -- 住所行政区划详情
    rlzl_detail TEXT,          -- 燃料种类详情
    xzqh_detail TEXT,          -- 管理辖区详情
    gcjk_detail TEXT,          -- 国产/进口详情
    zzjglx TEXT,               -- 组织机构类型
    zzxxdz TEXT,               -- 暂住详细地址
    zzxzqh TEXT,               -- 暂住行政区划
    fdjrq TEXT,                -- 发登记证书日期
    zbzl TEXT,                 -- 整备质量
    dphgzbh TEXT,              -- 底盘合格证编号
    etl_date TEXT,             -- ETL_DATE
    hxnbgd TEXT,               -- 货箱内部高度
    bdjcs TEXT,                -- 补/换领证书次数
    hdfs_detail TEXT,          -- 获得方式详情
    djzsbh TEXT,               -- 登记证书编号
    odc_cqsj TEXT,             -- ODC抽取时间
    hdzzl TEXT,                -- 核定载质量
    hbdbqk TEXT,               -- 环保达标情况
    qlj TEXT,                  -- 前轮距
    zxxs TEXT,                 -- 转向形式
    yzbm1 TEXT,                -- 住所邮政编码
    yzbm2 TEXT,                -- 暂住邮政编码
    nszm TEXT,                 -- 纳税证明
    dabh TEXT,                 -- 档案编号
    lsh TEXT,                  -- 注册流水号
    yqjyqzbfqz TEXT,           -- 逾期检验强制报废期止
    zt_detail TEXT,            -- 机动车状态详情
    syq TEXT,                  -- 所有权
    odc_zj TEXT,               -- ODC主键
    zqyzl TEXT,                -- 准牵引总质量
    xzqh TEXT,                 -- 管理辖区
    odc_jcbz TEXT,             -- ODC检查标志
    llpz1 TEXT,                -- 来历凭证1
    qpzk TEXT,                 -- 驾驶室前排载客人数
    xszbh TEXT,                -- 行驶证证芯编号
    llpz2 TEXT,                -- 来历凭证2
    dybj TEXT,                 -- 0-未抵押，1-已抵押
    fdjgs TEXT,                -- 发动机缸数
    hxnbkd TEXT,               -- 货箱内部宽度
    fdjxh TEXT,                -- 发动机型号
    hlj TEXT,                  -- 后轮距
    zzcmc TEXT,                -- 制造厂名称
    lts TEXT,                  -- 轮胎数
    rlzl TEXT,                 -- 燃料种类
    cwkk TEXT,                 -- 车外廓宽
    odc_gxsj TEXT,             -- ODC更新时间
    cwkg TEXT,                 -- 车外廓高
    gxrq TEXT,                 -- 更新日期
    glbm TEXT,                 -- 管理部门
    sfyzhgn TEXT,              -- 专项做车是否有载货功能1-是；2-否
    cwkc TEXT,                 -- 车外廓长
    bzcs TEXT,                 -- 补领行驶证次数
    hgzbh TEXT,                -- 合格证编号
    jkpzhm TEXT,               -- 进口凭证编号
    gl TEXT,                   -- 功率
    xsdw TEXT,                 -- 销售单位
    hdfs TEXT,                 -- 获得方式
    ytsx TEXT,                 -- 用途属性
    jyw TEXT,                  -- 校验位
    pzbh1 TEXT,                -- 凭证编号1
    xh TEXT,                   -- 机动车序号
    pzbh2 TEXT,                -- 凭证编号2
    hxnbcd TEXT,               -- 货箱内部长度
    pl TEXT,                   -- 排量
    zdyzt TEXT,                -- 自定义状态
    rzx_uuid TEXT,             -- rzx唯一编码
    kafka_createtime TEXT,     -- 接入kafka时间
    createtime_rzx TEXT,       -- 原表入库时间
    rzx_src TEXT,              -- 数据溯源
    rzx_id TEXT,               -- rzx根据规则生成的数据id
    rzx_src2 TEXT,             -- 数据溯源2
    inserttime_rzx TEXT,       -- 入库时间
    ch_partition TEXT          -- 分区字段
);

CREATE TABLE CASE_GL_AWGL ( -- 案件—物品关联表
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    QXGLR TEXT, -- 取消关联人
    QXGLSJ DATETIME, -- 取消关联时间
    WPBH TEXT, -- 物品编号
    AJBH TEXT, -- 案件编号
    TBSJ DATETIME, -- 同步时间
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_GL_DAGL ( -- 单位—案件关联表
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    QXGLR TEXT, -- 取消关联人
    QXGLSJ DATETIME, -- 取消关联时间
    DWBH TEXT, -- 单位编号
    AJBH TEXT, -- 案件编号
    SPYJ TEXT, -- 审批意见
    SPZT TEXT, -- 审批状态
    JCGL_REASON TEXT, -- 解除关联原因
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_GL_RAGL ( -- 人员—案件关联表
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    QXGLR TEXT, -- 取消关联人
    QXGLSJ DATETIME, -- 取消关联时间
    RYBH TEXT, -- 人员编号
    AJBH TEXT, -- 案件编号
    RYLX TEXT, -- 人员类型
    TBSJ DATETIME, -- 同步时间
    XGSJ DATETIME, -- 修改时间
    CBDW_BH TEXT, -- 承办单位编号
    CBQY_BH TEXT, -- 承办区域编号
    CREATETIME DATETIME, -- 创建时间
    ORDER_ID INTEGER, -- 排序
    JCGL_REASON TEXT, -- 解除关联原因
    SPZT TEXT, -- 审批状态
    SPYJ TEXT, -- 审批意见
    PRIMARY KEY (ID)
);

CREATE TABLE res_zh_gj_info (       -- 人员轨迹表
    id TEXT,                        -- 唯一标识
    trace_type TEXT,                -- 轨迹类型
    trace_type_name TEXT,           -- 轨迹类型名称
    id_card TEXT,                   -- 身份证号
    name TEXT,                      -- 姓名
    from_place TEXT,                -- 开始地点
    to_place TEXT,                  -- 到达地点
    start_time DATETIME,            -- 开始时间
    end_time DATETIME,              -- 到达时间
    batch_no TEXT,                  -- 轨迹批次
    trace_status TEXT,              -- 轨迹状态
    trace_status_name TEXT,         -- 轨迹状态名称
    phone_no TEXT,                  -- 手机号
    detail_info TEXT,               -- 详细信息
    trace_source TEXT,              -- 轨迹来源(表名)
    trace_source_name TEXT,         -- 轨迹来源(表中文名)
    remark TEXT,                    -- 备注
    capture_time DATETIME,          -- 采集时间
    address TEXT,                   -- 具体位置
    createtime_rzx TEXT,            -- 数据入ck时间
    create_time DATETIME,           -- 创建时间
    create_date DATE,               -- 创建时间
    car_number TEXT,                -- 车牌号
    from_place_location_code TEXT,  -- 出发地CODE
    to_place_location_code TEXT,    -- 到达地CODE
    from_place_longitude TEXT,      -- 出发地经度
    from_place_latitude TEXT,       -- 出发地纬度
    to_place_longitude TEXT,        -- 到达地经度
    to_place_latitude TEXT,         -- 到达地纬度
    from_place_address TEXT,        -- 出发地地址
    to_place_address TEXT,          -- 到达地地址
    hjdz_ssxqdm TEXT,               -- 户籍地代码（370102）
    hjdz_ssxqdm_detail TEXT,        -- 户籍地详细地址
    hjdz_qhnxxdz TEXT               -- 户籍地区划地（山东省济南市历下区）
);

CREATE TABLE rzx_wz_wldt_logs ( -- 网络轨迹表
    data_type TEXT,         -- 数据类型（4g,gw,wb,sj）
    app_type TEXT,          -- 来源表名（英文）
    app_type_name TEXT,     -- 来源表名（中文）
    protocol_type TEXT,     -- 协议英文（软件名称）
    protocol_type_name TEXT, -- 协议中文
    action TEXT,            -- 操作动作，例如发帖（字典）
    auth_account TEXT,      -- 认证账号（宽带账号，手机号,身份证）
    user_id TEXT,           -- 账号id
    username TEXT,          -- 账号
    nickname TEXT,          -- 昵称
    title TEXT,             -- 标题
    content TEXT,           -- 内容
    imgs TEXT,              -- 图片列表，文件列表
    tags TEXT,              -- 标签列表
    url TEXT,               -- 访问url
    capture_time TEXT,      -- 采集时间(13位时间戳)
    to_user_id TEXT,        -- 接收账号id
    to_username TEXT,       -- 接收账号
    to_nickname TEXT,       -- 接收昵称
    isp_id TEXT,            -- 运营商名称（汉字）
    base_station_id TEXT,   -- 基站ID
    equipment_id TEXT,      -- 设备id（IMEI）
    imsi TEXT,              -- IMSI
    longitude TEXT,         -- 经度
    latitude TEXT,          -- 纬度
    src_ip TEXT,            -- 源ip
    src_port TEXT,          -- 源端口
    dst_ip TEXT,            -- 目的ip
    dst_port TEXT,          -- 目的端口
    domain TEXT,            -- 域名
    password TEXT,          -- 密码
    other_info TEXT,        -- 其他信息
    mac TEXT,               -- mac
    keyword TEXT,           -- 关键词
    is_domestic TEXT,       -- 是否境内ip
    src_ip_address TEXT,    -- 具体地址
    dst_ip_address TEXT     -- 具体地址
);

CREATE TABLE CASE_XS_DBZ ( -- 刑事案件逮捕状
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    WSZT TEXT, -- 文书状态
    CBQY_BH TEXT, -- 承办单位区域
    AJBH TEXT, -- 案件编号
    CBDW_BH TEXT, -- 承办单位
    CBDW_MC TEXT, -- 承办单位名称
    CBDW_JC TEXT, -- 承办单位简称
    CBR_SFZH TEXT, -- 承办人
    CBR_XM TEXT, -- 承办人姓名
    TFSJ DATETIME, -- 填发时间
    WSH TEXT, -- 文书号
    AJMC TEXT, -- 案件名称
    PZR_SFZH TEXT, -- 批准人
    PZR_XM TEXT, -- 批准人姓名
    TFR_SFZH TEXT, -- 填发人
    TFR_XM TEXT, -- 填发人姓名
    PZSJ DATETIME, -- 批准时间
    RYBH TEXT, -- 嫌疑人编号
    RYXM TEXT, -- 嫌疑人姓名
    XYRXB TEXT, -- 嫌疑人性别
    XYRCSRQ DATETIME, -- 嫌疑人出生日期
    XYRZZ TEXT, -- 嫌疑人住址
    DBYY_C TEXT, -- 逮捕原因(存根)
    DBYY TEXT, -- 逮捕原因
    PZDBSJ DATETIME, -- 批准或决定逮捕时间
    PZHJDJG TEXT, -- 批准或决定机关
    PZJD TEXT, -- 批准/决定
    KSS_BH TEXT, -- 看守所编号
    KSS_MC TEXT, -- 看守所
    XBSJ DATETIME, -- 宣布时间
    JYSJ DATETIME, -- 羁押时间
    KSS_SFBH TEXT, -- 看守所民警
    KSS_XM TEXT, -- 看守所民警姓名
    KSSSJ DATETIME, -- 看守所时间
    ZXDBSJ DATETIME, -- 执行逮捕时间
    LSHJ TEXT, -- 律师会见（是/否）
    SIGNNAME TEXT, -- 公章名称
    PSIGNNAME TEXT, -- 公章落款
    PZWH TEXT, -- 逮捕决定书批准文号
    YWID TEXT, -- 呈请业务ID
    AY_BH TEXT, -- 案由编号
    AY_MC TEXT, -- 案由名称
    SFDA TEXT, -- 是否到案
    JDWS TEXT, -- 决定文书
    SFXZBL TEXT, -- 是否协助程序性笔录
    DASJ DATETIME, -- 到案时间
    ZXWS TEXT, -- 是否执行废弃
    SF TEXT, -- 区分是否执行文书
    ZCBM TEXT, -- 侦查部门
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_XS_JLZ ( -- 刑事案件拘留状
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    WSZT TEXT, -- 文书状态
    CBQY_BH TEXT, -- 承办单位区域
    AJBH TEXT, -- 案件编号
    CBDW_BH TEXT, -- 承办单位
    CBDW_MC TEXT, -- 承办单位名称
    CBDW_JC TEXT, -- 承办单位简称
    CBR_SFZH TEXT, -- 承办人
    CBR_XM TEXT, -- 承办人姓名
    TFSJ DATETIME, -- 填发时间
    WSH TEXT, -- 文书号
    AJMC TEXT, -- 案件名称
    PZR_SFZH TEXT, -- 批准人
    PZR_XM TEXT, -- 批准人姓名
    TFR_SFZH TEXT, -- 填发人
    TFR_XM TEXT, -- 填发人姓名
    PZSJ DATETIME, -- 批准时间
    RYBH TEXT, -- 嫌疑人编号
    RYXM TEXT, -- 嫌疑人姓名
    XYRXB TEXT, -- 嫌疑人性别
    XYRCSRQ DATETIME, -- 嫌疑人出生日期
    XYRZZ TEXT, -- 嫌疑人住址
    JLYY_C TEXT, -- 拘留原因(存根)
    JLYY TEXT, -- 拘留原因
    FLTK TEXT, -- 法律条款
    KSS_BH TEXT, -- 看守所编号
    KSS_MC TEXT, -- 看守所
    XBSJ DATETIME, -- 宣布时间
    DKSSSJ DATETIME, -- 到看守所时间
    SXZM TEXT, -- 涉嫌罪名
    ZXJLSJ DATETIME, -- 执行拘留时间
    LSHJ TEXT, -- 律师会见(是/否)
    JSMJ_SFBH TEXT, -- 接收民警
    JSMJ_XM TEXT, -- 接收民警姓名
    SIGNNAME TEXT, -- 公章名称
    PSIGNNAME TEXT, -- 公章落款
    YWID TEXT, -- 呈请业务ID
    AY_BH TEXT, -- 案由编号
    AY_MC TEXT, -- 案由名称
    SFDA TEXT, -- 是否到案
    JDWS TEXT, -- 决定文书
    SFXZBL TEXT, -- 是否协助程序性笔录
    DASJ DATETIME, -- 到案时间
    SF TEXT, -- 是否拘留
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_XS_JSJZJDZXTZS ( -- 刑事监视居住决定执行通知
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    WSZT TEXT, -- 文书状态
    CBQY_BH TEXT, -- 承办单位区域
    AJBH TEXT, -- 案件编号
    CBDW_BH TEXT, -- 承办单位
    CBDW_MC TEXT, -- 承办单位名称
    CBDW_JC TEXT, -- 承办单位简称
    CBR_SFZH TEXT, -- 承办人
    CBR_XM TEXT, -- 承办人姓名
    TFSJ DATETIME, -- 填发时间
    WSH TEXT, -- 文书号
    AJMC TEXT, -- 案件名称
    PZR_SFZH TEXT, -- 批准人
    PZR_XM TEXT, -- 批准人姓名
    PZSJ DATETIME, -- 批准时间
    RYBH TEXT, -- 嫌疑人编号
    RYXM TEXT, -- 嫌疑人姓名
    XYRXB TEXT, -- 嫌疑人性别
    XYRCSRQ DATETIME, -- 嫌疑人出生日期
    XYRZZ TEXT, -- 嫌疑人住址
    JSYY_C TEXT, -- 监视居住原因(存根)
    JSYY TEXT, -- 监视居住原因
    JSDD TEXT, -- 监视居住地点
    SFZDJS TEXT, -- 是否指定居所
    QSSJ DATETIME, -- 起算时间
    ZXJG TEXT, -- 执行机关
    FLYJ TEXT, -- 法律依据
    JSJZLX TEXT, -- 监视居住类型
    QZSJ DATETIME, -- 签字时间
    SFHJLS TEXT, -- 是否属会见律师
    TFR_SFZH TEXT, -- 填发人
    TFR_XM TEXT, -- 填发人姓名
    SXZM TEXT, -- 涉嫌罪名
    SIGNNAME TEXT, -- 公章名称
    PSIGNNAME TEXT, -- 公章落款
    JJLX TEXT, -- 监居类型
    YWID TEXT, -- 呈请业务ID
    JDWS TEXT, -- 决定文书
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_XS_LAJDS ( -- 刑事案件立案决定书
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    WSZT TEXT, -- 文书状态
    CBQY_BH TEXT, -- 承办单位区域
    AJBH TEXT, -- 案件编号
    CBDW_BH TEXT, -- 承办单位
    CBDW_MC TEXT, -- 承办单位名称
    CBDW_JC TEXT, -- 承办单位简称
    CBR_SFZH TEXT, -- 承办人
    CBR_XM TEXT, -- 承办人姓名
    TFSJ DATETIME, -- 填发时间
    WSH TEXT, -- 文书号
    AJMC TEXT, -- 案件名称
    RYBH TEXT, -- 嫌疑人编号
    RYXM TEXT, -- 嫌疑人姓名
    XYRXB TEXT, -- 嫌疑人性别
    XYRCSRQ DATETIME, -- 嫌疑人出生日期
    XYRZZ TEXT, -- 嫌疑人住址
    XYRDWZY TEXT, -- 嫌疑人单位职业
    PZR_SFZH TEXT, -- 批准人
    PZR_XM TEXT, -- 批准人姓名
    PZSJ DATETIME, -- 批准时间
    FLTK TEXT, -- 法律条款
    TFR_XM TEXT, -- 填发人姓名
    TFR_SFZH TEXT, -- 填发人
    SIGNNAME TEXT, -- 公章名称
    PSIGNNAME TEXT, -- 公章落款
    YWID TEXT, -- 呈请业务ID
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_XS_QBHSJDZXTZS ( -- 刑事取保候审决定通知书
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 数据是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    WSZT TEXT, -- 文书状态
    CBQY_BH TEXT, -- 承办单位区域
    AJBH TEXT, -- 案件编号
    CBDW_BH TEXT, -- 承办单位编号
    CBDW_MC TEXT, -- 承办单位名称
    CBDW_JC TEXT, -- 承办单位简称
    CBR_SFZH TEXT, -- 承办人身份证号
    CBR_XM TEXT, -- 承办人姓名
    TFSJ DATETIME, -- 填发时间
    WSH TEXT, -- 文书号
    AJMC TEXT, -- 案件名称
    PZR_SFZH TEXT, -- 批准人身份证号
    PZR_XM TEXT, -- 批准人姓名
    PZSJ DATETIME, -- 批准时间
    RYBH TEXT, -- 嫌疑人编号
    RYXM TEXT, -- 嫌疑人姓名
    XYRXB TEXT, -- 嫌疑人性别
    XYRCSRQ DATETIME, -- 嫌疑人出生日期
    QBYY_C TEXT, -- 取保原因(存根)
    QBYY TEXT, -- 取保原因
    QISUANSHIJIAN DATETIME, -- 起算时间
    BZRXM TEXT, -- 保证人姓名
    BZRXB TEXT, -- 保证人性别
    BZRCSRQ DATETIME, -- 保证人出生日期
    BZJ TEXT, -- 保证金
    QBLX TEXT, -- 取保候审类型
    ZXJG TEXT, -- 执行机关
    XYRZZ TEXT, -- 嫌疑人住址
    XYRDWJZY TEXT, -- 嫌疑人单位及职业
    XYRLXFS TEXT, -- 嫌疑人联系方式
    QZSJ DATETIME, -- 签字时间
    TFR_SFZH TEXT, -- 填发人身份证号
    TFR_XM TEXT, -- 填发人姓名
    FLYJ TEXT, -- 法律依据
    SIGNNAME TEXT, -- 公章名称
    QBJD TEXT, -- 取保决定
    JRCS TEXT, -- 进入场所
    HJR TEXT, -- 会见人员
    CSHD TEXT, -- 从事活动
    ZJMC TEXT, -- 证件名称
    PSIGNNAME TEXT, -- 公章落款
    QBLX2 TEXT, -- 取保类型2
    BZJ_XX TEXT, -- 保证金（小写）
    YWID TEXT, -- 呈请业务ID
    ZBDW_MC TEXT, -- 侦办单位名称
    AY_BH TEXT, -- 案由编号
    AY_MC TEXT, -- 案由名称
    BPBYY TEXT, -- 不批捕原因
    JDWS TEXT, -- 决定文书
    QBJG TEXT, -- 取保价格
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_XZ_SADJB ( -- 行政案件受案登记表
    ID TEXT, -- 唯一标识
    ISDEL INTEGER, -- 是否逻辑删除
    DATAVERSION TEXT, -- 数据版本号
    LRR_SFZH TEXT, -- 录入人
    LRSJ DATETIME, -- 录入时间
    XGR_SFZH TEXT, -- 修改人
    XGSJ DATETIME, -- 修改时间
    WSZT TEXT, -- 文书状态
    CBQY_BH TEXT, -- 承办单位区域
    AJBH TEXT, -- 案件编号
    CBDW_BH TEXT, -- 受理单位编号
    CBDW_MC TEXT, -- 受理单位名称
    CBDW_JC TEXT, -- 部门简称
    CBR_SFZH TEXT, -- 受理人身份证号
    CBR_XM TEXT, -- 受理人姓名
    AYBH TEXT, -- 案由编号
    AYMC TEXT, -- 案由名称
    AJMC TEXT, -- 案件名称
    AJLY TEXT, -- 案件来源
    SLSJ DATETIME, -- 受理时间
    BAR_XM TEXT, -- 报案人姓名
    BAR_XB TEXT, -- 报案人性别
    BAR_CSRQ DATETIME, -- 报案人出生日期
    BAR_DW TEXT, -- 报案人单位
    BAR_LXFS TEXT, -- 报案人联系方式
    BAR_ZZ TEXT, -- 报案人住址
    BAR_ZJZL TEXT, -- 报案人证件种类
    BAR_ZJHM TEXT, -- 报案人证件号码
    BASJ DATETIME, -- 报案时间
    YSDW TEXT, -- 移送单位
    YSRXM TEXT, -- 移送单位承办人
    YSDWLXDH TEXT, -- 移送单位联系电话
    JYAQ TEXT, -- 简要案情
    YSDWMC TEXT, -- 移送单位名称
    YSR TEXT, -- 移送人
    SLYJ TEXT, -- 受理意见
    WSH TEXT, -- 文书号
    JQBH TEXT, -- 警情编号
    JBR TEXT, -- 接报人
    JBRXM TEXT, -- 接报人姓名
    JBDD TEXT, -- 接报地点
    SWDW TEXT, -- 送往单位
    SAYJ1 TEXT, SAYJ2 TEXT, SAYJ3 TEXT, SAYJ4 TEXT, SAYJ5 TEXT, -- 受案意见1-5
    QT TEXT, -- 其他
    SFJSZJ TEXT, -- 是否接收证据
    FASJ DATETIME, -- 发案时间
    SAYJ TEXT, -- 受案意见总
    SIGNNAME TEXT, -- 公章名称
    GLZJQDID TEXT, -- 关联证据清单ID
    ISYTZJQD TEXT, -- 是否已填证据清单
    LRR_XM TEXT, -- 录入人姓名
    FADD TEXT, -- 发案地点
    ZBDWJZ TEXT, -- 主办单位警种
    PSIGNNAME TEXT, -- 公章落款
    SWDWBH TEXT, -- 送往单位编号
    ABXL1 TEXT, ABXL1_NAME TEXT, -- 案由编号/名称1
    ABXL2 TEXT, ABXL2_NAME TEXT, -- 案由编号/名称2
    ABXL3 TEXT, ABXL3_NAME TEXT, -- 案由编号/名称3
    SFGK TEXT, -- 是否公开
    BGKYY TEXT, -- 不公开原因
    AJLXBH TEXT, -- 案件类型编号
    AJLXMC TEXT, -- 案件类型名称
    ZABS TEXT, -- 专案标识
    SQ TEXT, -- 社区
    SFKB TEXT, -- 是否快速办理
    SQBH TEXT, -- 社区编号
    XZQY TEXT, -- 行政区域
    BZDZ TEXT, -- 标准地址
    BZDZBH TEXT, -- 标准地址编号
    BCSM TEXT, -- 补充说明
    ZBX TEXT, ZBY TEXT, -- 坐标
    XZQYBH TEXT, -- 行政区域编号
    SHRSFSW TEXT, -- 受害人是否死亡
    SHR INTEGER, -- 死亡人数
    SFSY TEXT, -- 是否涉疫
    ABXLMX TEXT, ABXLMX_NAME TEXT, -- 案由明细编号与名称
    SFFF TEXT, -- 是否非访
    PRIMARY KEY (ID)
);

CREATE TABLE CASE_XZ_XZCFJDS ( -- 行政处罚决定书
    ID TEXT,                         -- 唯一标识
    ISDEL INTEGER,                   -- 是否逻辑删除
    DATAVERSION TEXT,                -- 数据版本号
    LRR_SFZH TEXT,                   -- 录入人身份证号
    LRSJ DATETIME,                   -- 录入时间
    XGR_SFZH TEXT,                   -- 修改人身份证号
    XGSJ DATETIME,                   -- 修改时间
    WSZT TEXT,                       -- 文书状态
    CBQY_BH TEXT,                    -- 承办单位区域编号
    AJBH TEXT,                       -- 案件编号
    CBDW_BH TEXT,                    -- 承办单位编号
    CBDW_MC TEXT,                    -- 承办单位名称
    CBDW_JC TEXT,                    -- 承办单位简称
    CBR_SFZH TEXT,                   -- 承办人身份证号
    CBR_XM TEXT,                     -- 承办人姓名
    TFSJ DATETIME,                   -- 填发时间
    WSH TEXT,                        -- 文书号
    AJMC TEXT,                       -- 案件名称
    RYBH TEXT,                       -- 违法行为人编号
    RYXM TEXT,                       -- 违法行为人姓名
    DWBH TEXT,                       -- 被处罚单位编号
    DWMC TEXT,                       -- 被处罚单位名称
    RYXX TEXT,                       -- 违法行为人信息
    WFSS TEXT,                       -- 违法事实
    ZJ TEXT,                         -- 相关证据
    FLYJ TEXT,                       -- 法律依据
    XZCFJD TEXT,                     -- 行政处罚决定
    LXFS TEXT,                       -- 履行方式
    FYJG TEXT,                       -- 复议机关
    RMFY TEXT,                       -- 人民法院
    QDLX TEXT,                       -- 清单类型
    QDFS TEXT,                       -- 清单份数
    QZSJ DATETIME,                   -- 签字时间
    SIGNNAME TEXT,                   -- 公章名称
    CFLX TEXT,                       -- 裁决类型
    GAJGNAME_BT TEXT,                -- 公安机关名称（标题）
    MEMO TEXT,                       -- 备注
    CFJG TEXT,                       -- 处罚结果
    CQCZ TEXT,                       -- 从轻从重意见
    ZXQK TEXT,                       -- 执行情况
    QD TEXT,                         -- 清单内容
    QD1 TEXT,                        -- 清单内容备用
    WFSS1 TEXT,                      -- 违法事实（备用）
    ZS TEXT,                         -- 综述
    ZJ1 TEXT,                        -- 默认证据
    PSIGNNAME TEXT,                  -- 公章落款
    CBQY_MC TEXT,                    -- 承办区域名称
    SPSJ DATETIME,                   -- 审批时间
    SPRXM TEXT,                      -- 审批人姓名
    SFGK TEXT,                       -- 是否公开
    BF TEXT,                         -- 边防单位
    KSS_BH TEXT,                     -- 看守所编号
    KSS_MC TEXT,                     -- 看守所名称

    -- 统计项
    TJ_JLTS INTEGER,                 -- 拘留天数（总）
    TJ_FKJE INTEGER,                 -- 罚款金额（元）
    TJ_JG INTEGER,                   -- 是否警告（1/0）
    TJ_DX INTEGER,                   -- 是否吊销（1/0）
    TJ_QT TEXT,                      -- 其他处罚
    TJ_ZDTS INTEGER,                 -- 折抵天数（数值）
    TJ_ZDTS_CN TEXT,                 -- 折抵天数（中文）
    TJ_ZDTK TEXT,                    -- 折抵条款
    TJ_ZLTKNR TEXT,                  -- 责令条款内容

    -- HTML 和纯文本字段（可用于模板渲染与归档）
    JLBZX TEXT,                      -- 拘留不执行标识
    CFJG_HTML TEXT,                  -- 处罚结果（HTML格式）
    ZXQK_HTML TEXT,                  -- 执行情况（HTML格式）
    IS_CF TEXT,                      -- 是否已处罚
    CFJG_TEXT TEXT,                  -- 处罚结果（纯文本）
    ZXQK_TEXT TEXT,                  -- 执行情况（纯文本）

    SFKSBL TEXT,                     -- 是否快速办理
    PRIMARY KEY (ID)
);

